### ISSUE TITLE
Crash when building bounding box on an empty tree

### ISSUE THREAD

**Issue by lsouchet** [OctoMap/octomap#109]
Hello,
I encountered a crash (SIGSEGV) when iterating over an empty octree through bounding boxes.
The crash occurs inside OcTreeBaseImpl<NODE,I>::coordToKeyChecked() after the call to begin_leafs_bbx().

[This commit](https://github.com/lsouchet/octomap/commit/05f7aee5d455b4db1f43ddbf7e4c4a6b086d01aa) contains a unit test to reproduce.

My workaround consist in checking my tree size before iterating over it, but I think it would be safer for this check to be done within the begin_leafs_bbx().

What do you think?

Thanks!

**Comment by ahornung** [comment]
Yes, that looks like a bug. I think there's a special check for an empty tree missing (previous an empty tree contained *only* a root node, now it's really empty).
