### ISSUE TITLE
  Can't use cmake to build Octovis with Qt5

### ISSUE THREAD

**Issue by kingstarcraft** [OctoMap/octomap#110]
Error when I use cmake bulid Octomap :
viewer octovis will be built
CMake Error at D:/CMake/share/cmake-3.3/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.5.1" from
  D:/Qt/5.5/msvc2013_64/bin/qmake.exe, this code requires Qt 4.x
Call Stack (most recent call first):
  octovis/CMakeLists_src.txt:2 (find_package)
  octovis/CMakeLists.txt:84 (INCLUDE)

**Comment by ahornung** [comment]
octovis currently requires (and was only tested using) Qt4

**Comment by aseidman** [comment]
@kingstarcraft ran into the same issue. have you found a work-around to this problem?

**Comment by ahornung** [comment]
If you don't actually need octovis then you can skip compiling it, it makes many things in Windows easier (there's a CMake option for it).

Generally, compilation is smoother in Ubuntu/Debian using the precompiled libs for QGLViewer.

**Comment by codegrafix** [comment]
On ubuntu you can install qmake-qt4 and update the qmake link:
sudo update-alternatives --install /usr/bin/qmake qmake /usr/bin/qmake-qt4 40

Next set standard link with: sudo update-alternatives --config qmake to qt4!

**Comment by mhkabir** [comment]
@ahornung Are there any plans to support Qt 5 for Octovis? We want to integrate the visualizer component into another Qt application which is based on Qt 5.x.

**Comment by ahornung** [comment]
There's a new qt5-branch available (check out `qt5-support`), which optionally allows you to build with Qt5. Could you test it out?

**Comment by kingstarcraft** [comment]
@ahornung thanks your reply, I have solved the problem by changing the compiler(qt4) .
