### ISSUE TITLE
Cannot open liboctomap.dll when compiling with VS2010

### ISSUE THREAD

**Issue by Richardche** [OctoMap/octomap#111]
I generated the correct solution file octomap-distribution.sln using CMAKE. 
But when I built the solution using VS2010, I found that liboctomap.dll cannot be found:

Error	166	error LNK1104: cannot open file '..\..\..\lib\liboctomap.dll'	E:\octomap\octomap-1.7.0\build\dynamicEDT3D\src\LINK
Error	293	error LNK1104: cannot open file '..\..\lib\liboctomap.dll'	E:\octomap\octomap-1.7.0\build\octovis\LINK
Error	459	error LNK1104: cannot open file '..\..\..\..\lib\liboctomap.dll'	E:\octomap\octomap-1.7.0\build\dynamicEDT3D\src\examples\LINK
Error	463	error LNK1104: cannot open file '..\..\..\..\lib\liboctomap.dll'	E:\octomap\octomap-1.7.0\build\dynamicEDT3D\src\examples\LINK
Error	594	error LNK1104: cannot open file '..\..\lib\liboctomap.dll'	E:\octomap\octomap-1.7.0\build\octovis\LINK

     I looked up in the solution explorer and I couldn't find the target generation for this. 
Which target corresponds to this dll file? How to solve this problem?

**Comment by ahornung** [comment]
Could you update to the latest version? 1.7.1 should have fixed that.

**Comment by Richardche** [comment]
The latest version works! Thanks!
