### ISSUE TITLE
Inserting pointcloud after clear() fails.

### ISSUE THREAD

**Issue by skasperski** [OctoMap/octomap#123]
Hello,

I am building an octomap::OcTree from pointclouds, which works fine so far. But when I call clear() on the OcTree and then try to add a new pointcloud, it crashes without an exception. Is there anything that has to be done after calling clear(), before new pointclouds can be inserted again?

Edit: A run with gdb gave me:

    Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fff9f7fe700 (LWP 11343)]
    0x00007fffecf3c174 in octomap::OcTreeBaseImpl<octomap::OcTreeNode, octomap::AbstractOccupancyOcTree>::search(octomap::OcTreeKey const&, unsigned int) const ()

Best regards,
Sebastian

**Comment by ahornung** [comment]
I can confirm that a quick test with `clear()` already segfaults for me using the latest version, even without inserting anything afterwards. It does not happen with 1.7.0 so it's probably related to the changes introduced with #98.

**Comment by ahornung** [comment]
Fixed in devel, could you try it out?

**Comment by skasperski** [comment]
Works on my side.
