### ISSUE TITLE
Broken octovis-config.cmake if @QGLViewer_LIBRARY_DIR@ is empty

### ISSUE THREAD

**Issue by chhtz** [OctoMap/octomap#129]
This will result in an empty string passed to a `set_and_check` command causes an error.
The quickest workaround is to lose the `""`, but that is likely to break if the directory is not empty and contains spaces.

**Comment by chhtz** [comment]
Looking at how `set_and_check` is defined, this seems to be broken anyway, since `set_and_check` only considers the first file (or directory). So how about just losing the ` "@QGLViewer_INCLUDE_DIR@"` and `"@QGLViewer_LIBRARY_DIR@"` inside /octovis/octovis-config.cmake.in entirely?

**Comment by ahornung** [comment]
I switched the order as suggested in #130. This probably needs a second look to check which paths are needed at all, but it should work for now.
