### ISSUE TITLE
Binary read and write of log file is bugged

### ISSUE THREAD

**Issue by andresax** [OctoMap/octomap#131]
Hi,

thanks for the great tool you made available for the whole community.

I found an issue during the data import of a log file. In the PointCloud.cpp source the binary read and write are not symmetric, and so the reading fails.
I'm referring in particular at:
https://github.com/OctoMap/octomap/blob/devel/octomap/src/Pointcloud.cpp#L287
and
https://github.com/OctoMap/octomap/blob/devel/octomap/src/Pointcloud.cpp#L313

where an unsigned int it is read, while a size_t is written.

I suggest also to fix line 
https://github.com/OctoMap/octomap/blob/devel/octomap/src/Pointcloud.cpp#L294 with size_t instead of unsigned int.

Cheers,
Andrea

**Comment by ahornung** [comment]
Good catch! We really need a unit test for these IO operations, just like the OcTree tests. 

But I think the types should be fixed size  to make it really portable. Just like unsigned int, size_t can be different on different platforms. Reference should be the existing graph files from the homepage (I think they were written with uint).

**Comment by ahornung** [comment]
Fixed now.
