### ISSUE TITLE
Build error: "export could not write export file"

### ISSUE THREAD

**Issue by mikepurvis** [OctoMap/octomap#142]
See:

```
16:30:56 Errors << octomap:cmake /tmp/buildd/workspace/debian/tmp/build/logs-autonomy/octomap/build.cmake.000.log
16:30:56 
16:30:56 
16:30:56 CMake Error: cannot write to file "/tmp/buildd/workspace/octomap-6d7c31ae4df2c93cb8a954e44d442338b58d3558/octomap/lib/cmake/octomap/octomap-targets.cmake": No such file or directory
16:30:56 CMake Error at /tmp/buildd/workspace/octomap-6d7c31ae4df2c93cb8a954e44d442338b58d3558/octomap/src/math/CMakeLists.txt:20 (export):
16:30:56   export could not write export file.
16:30:56 
16:30:56 
16:30:56 CMake Error: cannot write to file "/tmp/buildd/workspace/octomap-6d7c31ae4df2c93cb8a954e44d442338b58d3558/octomap/lib/cmake/octomap/octomap-targets.cmake": No such file or directory
16:30:56 CMake Error at /tmp/buildd/workspace/octomap-6d7c31ae4df2c93cb8a954e44d442338b58d3558/octomap/src/CMakeLists.txt:24 (export):
16:30:56   export could not write export file.
16:30:56 
```

Reverting to before #140 merged resolves the issue.

**Comment by ahornung** [comment]
Strange, maybe @jamiesnape has an idea?

**Comment by jamiesnape** [comment]
Does the directory
`/tmp/buildd/workspace/octomap-6d7c31ae4df2c93cb8a954e44d442338b58d3558/octomap/lib/cmake/octomap/` exist and is it writeable by the user performing the build?

**Comment by mikepurvis** [comment]
Looks like this is at least partly down to a bug in old CMake. On Ubuntu Trusty (CMake 2.8.12.2):

```
mkdir src
git clone https://github.com/OctoMap/octomap src/octomap --depth 1
catkin config --install --isolate-devel
catkin build octomap
```

Error is:

```
CMake Error: cannot write to file "<ws>/src/octomap/octomap/lib/cmake/octomap/octomap-targets.cmake": No such file or directory
CMake Error at /home/mpurvis/octo_ws/src/octomap/octomap/src/math/CMakeLists.txt:20 (export):
  export could not write export file.
```

However, doing the exact same under Homebrew (CMake 3.6.2) succeeds just fine, and the following three files are created:

```
./build/octomap/src/CMakeFiles/Export/share/octomap/octomap-targets.cmake
./install/share/octomap/octomap-targets.cmake
./src/octomap/octomap/lib/cmake/octomap/octomap-targets.cmake
```

So first of all, I don't think it's correct behaviour to be generating these into the source folder— they should go in the build tree. But the larger issue is that `export()` on new-CMake creates the folder, which old-CMake doesn't do.

Would we entertain a PR that pre-creates the missing path if it doesn't exist?

**Comment by jamiesnape** [comment]
> So first of all, I don't think it's correct behaviour to be generating these into the source folder— they should go in the build tree.
 
Definitely, see #133.

**Comment by ahornung** [comment]
Yes, #133 needs to be handled, but for a future minor release (not patch level).

It's strange though that the other generated files (package and version config) are written fine. At this point, I think there should be either a workaround, or revert of #140 and postponing it until #133 is resolved.

**Comment by jamiesnape** [comment]
I will PR a workaround shortly.
