### ISSUE TITLE
See Octmap voxels during a scan?

### ISSUE THREAD

**Issue by ScottJohnson2718** [OctoMap/octomap#144]
Is there a way to see in real time the voxels being created and destroyed while PointClouds are being merged in?  I saw the extensions to RViz but they aren't the actual voxels.  I'd like to see things are they are in Octoviz.  But Octoviz needs a .ot file to view.  Does this exist or would it need to be written?

**Comment by ahornung** [comment]
If you use octomap_rviz_plugins then the 3D map display will be exactly what octovis is showing, provided your machine is fast enough to handle the updates and rendering.

Anyways, for general questions best use the OctoMap mailing list, the repositories [octomap_mapping](https://github.com/OctoMap/octomap_mapping) for octomap_server in ROS and [octomap_rviz_plugins](https://github.com/OctoMap/octomap_rviz_plugins) for the RViz visualization. This issue tracker should be used for the core OctoMap library (I'm assuming you're using ROS from mentioning of RViz).
