### ISSUE TITLE
undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'

### ISSUE THREAD

**Issue by KahnShi** [OctoMap/octomap#145]
Hi all,

I met a problem when trying to make a simple ros example by moving and compiling simple_example.cpp into my ros workspace, and my CMakeLists.txt and package.xml were modified as http://wiki.ros.org/octomap.
My octomap code is devel branch from github.

However, when I tried to compile my package, the error happened as my tittle.
From #98 I know createChild is already been removed, so I felt very wired that it still needs createChild.
Could anyone give me some advice? THX! 

`
CMakeFiles/octomap_example.dir/src/octomap_example.cpp.o: In function 'octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::updateNodeRecurs(octomap::OcTreeNode*, bool, octomap::OcTreeKey const&, unsigned int, float const&, bool)':
octomap_example.cpp:(.text._ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16updateNodeRecursEPS1_bRKNS_9OcTreeKeyEjRKfb[_ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16updateNodeRecursEPS1_bRKNS_9OcTreeKeyEjRKfb]+0x146): undefined reference to 'octomap::OcTreeNode::createChild(unsigned int)'
CMakeFiles/octomap_example.dir/src/octomap_example.cpp.o: In function 'octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::readBinaryNode(std::istream&, octomap::OcTreeNode*) const':
octomap_example.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x1cb): undefined reference to 'octomap::OcTreeNode::createChild(unsigned int)'
octomap_example.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x2e2): undefined reference to 'octomap::OcTreeNode::createChild(unsigned int)'
octomap_example.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x3f6): undefined reference to 'octomap::OcTreeNode::createChild(unsigned int)'
octomap_example.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x50c): undefined reference to 'octomap::OcTreeNode::createChild(unsigned int)'
CMakeFiles/octomap_example.dir/src/octomap_example.cpp.o:octomap_example.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x617): more undefined references to 'octomap::OcTreeNode::createChild(unsigned int)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [/home/shi/ros/shi_catkin_ws/devel/.private/.../octomap_example] Error 1
make[1]: *** [CMakeFiles/octomap_example.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by KahnShi** [comment]
Problem solved.
I found that before I complied from the source indigo binary version of octomap, which I installed by apt-get, is still left in my PC, which seems to be not the exactly same version with devel branch.(?) @ahornung 
When I delete these installation and the header files in /opt/ros/indigo/include, problem is solved.

By the way, if I choose to delete all my octomap source codes and keep that binary installation and header files, same problems remain. Could there be anyone give me some hints?

THX!

**Comment by ahornung** [comment]
I don't think you're supposed to manually delete files from /opt/ros/... (unless you manually installed them there). This will leave you with an inconsistent and potentially non-functional ROS installation.

Mixing different binary versions of the library will create all kinds of unforeseeable bugs and behavior. So best uninstall the old binary package completely (`apt-get remove ...`) and recompile from source. However, this will also remove any ROS package that depends on the library. The catkin way would be to create an overlay in your source workspace and then depend on that source only.

**Comment by HuaYuXiao** [comment]
I ran into similar issue, and have successfully solved yet. 
Check this for help: https://github.com/HuaYuXiao/plan_env/issues/1
