### ISSUE TITLE
getUnknownLeafCenters centers not aligned with true leaf centers

### ISSUE THREAD

**Issue by aecins** [OctoMap/octomap#146]
Function `getUnknownLeafCenters` takes as a parameter a bounding box (`point3d pmin, point3d pmax`) and returns the centers of the unknown (occluded) leafs. However, the returned centers are not aligned to the true leaf centers. Instead they are aligned to the the input bounding box parameter `pmin`. See [lines 1061-1079 in OcTreeBaseImpl.hxx](https://github.com/OctoMap/octomap/blob/e19c1f33f92495e546175d64eb88fc40f16b62da/octomap/include/octomap/OcTreeBaseImpl.hxx#L1061-L1079).
A possible fix is to clamp `pmin` and `pmax` to the nearest leaf center coordinates e.g.:
```
octomap::OcTreeKey pmin_key = this->coordToKey(pmin, depth);
octomap::point3d pmin_clamped = this->keyToCoord(pmin_key, depth);
octomap::OcTreeKey pmax_key = this->coordToKey(pmax, depth);
octomap::point3d pmax_clamped = this->keyToCoord(pmax_key, depth);
```

**Comment by ahornung** [comment]
Any chance for a PR with the fix? Thanks!

**Comment by aecins** [comment]
I have created a pull request with a fix. Sorry it took a while, holidays =)
