### ISSUE TITLE
Count visible occupied cells

### ISSUE THREAD

**Issue by LAR-UFSC** [OctoMap/octomap#156]
Is there any way to count the visible occupied cells, because if I count all the occupied cells it will take into account the inner occupied cells. Like, if I have a sphere and just wants to know how many cells have in the surface, the ones inside the sphere isn't important in this point.
Thanks.

**Comment by ahornung** [comment]
There are no functions available in OctoMap that take visibility information into account.

For all occupied cells, you could check if all of their neighbors are occupied and ignore the cell in that case.

**Comment by LAR-UFSC** [comment]
Thanks, I was think to do exactly what you said. 

Although in that case I'll have to evaluate the neighbours of all the cells and then losing the velocity of the octomap.
