### ISSUE TITLE
Use in high speed robot?

### ISSUE THREAD

**Issue by imle** [OctoMap/octomap#159]
Is Octomap fast enough for use in a robot which regularly travels at speeds of 40 to 50 mph? If so, what are the areas of the code that would be most stressed?

**Comment by ahornung** [comment]
You'll definitely have to look far ahead to account for the delay due to the processing time, and in addition optimize / trade off the resolution. The part most stressed is the 3D raycasting, which is directly influenced by the maximum measurement range and resolution.

You can have a look at the OctoMap journal paper to get an idea about the performance, although it should be a bit more efficient by now.

**Comment by stevenimle** [comment]
Thanks for the reply. I have read the paper about the performance and don't remember coming across anything that specifically alluded to the raycasting timing. Would enabling the threading help remedy this delay?

If it helps, I can offer up more about our specific setup and input devices?

**Comment by ahornung** [comment]
Yes, given enough CPU power and threads available, you should definitely enable the OpenMP option.

In the end, there's no way around benchmarking and optimizing for your specific use case. Preprocessing to remove any unneeded points also always helps (e.g., do you need all points or only a specific height interval?)

**Comment by stevenimle** [comment]
When OpenMP is enabled, should I see a jump in all CPUs? The activity monitor shows no significant increase in activity among the other cores in our CPU.

I have spent some time optimizing the config parameters to ignore all of the unnecessary points above and below us. Is there any way to programmatically limit the field of view?

**Comment by ahornung** [comment]
Yes, you should see an increased load and faster processing times e.g. in the `graph2tree` tool. You could also debug by setting breakpoints or outputs at the parallelized code blocks (look for `#ifdef _OPENMP` in the code).

You can directly limit the maximum range, and there's also a bounding box that can be set and enabled, although I'm not sure it's fully functional.
