### ISSUE TITLE
Subdividing Octrees

### ISSUE THREAD

**Issue by jacquelinekay** [OctoMap/octomap#160]
Given an OcTree, I'd like to be able to subdivide the OcTree into uniformly sized "tiles" and save those tiles as individual OcTrees. I am having difficulty figuring out how to do this; it appears with the current API that this task is nontrivial. Using a bounding box iterator it's easy to iterate over the nodes that I want to include in the tile, but it seems like there are no convenience utilities for taking a subdivision of metric space and stuffing that into a new, valid OcTree.

Conceptually it makes sense that a subtree of the octree is a contiguous subdivision of 3D space, although you would have to adjust the resolution of the subtree.

@ahornung do you have any ideas for how I could implement this?

**Comment by ahornung** [comment]
I don't think there's an easy way with a current API, although it should be possible to implement.
