### ISSUE TITLE
Error linking custom code against dynamicEDT3D on Ubuntu 14.04

### ISSUE THREAD

**Issue by swethmandava** [OctoMap/octomap#161]
I installed ros packages of octomap and dynamic edt3d. I'm running something very similar to exampleEDTOctomap.cpp but I get the following error. 

CMakeFiles/get_occupancy.dir/src/get_occupancy.cpp.o: In function `CollisionCheck::CollisionCheck()':
get_occupancy.cpp:(.text._ZN14CollisionCheckC2Ev[_ZN14CollisionCheckC5Ev]+0x647): undefined reference to `DynamicEDTOctomap::DynamicEDTOctomap(float, octomap::OcTree*, octomath::Vector3, octomath::Vector3, bool)'
get_occupancy.cpp:(.text._ZN14CollisionCheckC2Ev[_ZN14CollisionCheckC5Ev]+0x65b): undefined reference to `DynamicEDTOctomap::update(bool)'
get_occupancy.cpp:(.text._ZN14CollisionCheckC2Ev[_ZN14CollisionCheckC5Ev]+0x66b): undefined reference to `DynamicEDTOctomap::~DynamicEDTOctomap()'
get_occupancy.cpp:(.text._ZN14CollisionCheckC2Ev[_ZN14CollisionCheckC5Ev]+0x73c): undefined reference to `DynamicEDTOctomap::~DynamicEDTOctomap()'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/swethmandava/Documents/demo/devel/lib/inspection_by_planes/get_occupancy] Error 1
make[1]: *** [ui_inspection_by_planes/inspection_by_planes/CMakeFiles/get_occupancy.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

It seems pretty straightforward at first but those functions definitions do exist except the following constructor.
DynamicEDTOctomap::DynamicEDTOctomap(float, octomap::OcTree*, octomath::Vector3, octomath::Vector3, bool)
I do pass octomap::point3d variables but it tries to call with octomath::Vector3 for somereason.

 Any leads are appreciated. Thanks!

**Comment by ahornung** [comment]
Please provide more details, which version of OctoMap are you trying to compile? Did you check out the latest version? Do you have another version installed that could interfere?

To reproduce, please post a minimal example. The code usually builds fine on the build server, so I don't thinks there's an inherent linking problem.

**Comment by JinglinZhang** [comment]
Maybe you need to add these lines in your CMakeLists.txt
```
find_package(octomap REQUIRED)
find_package(dynamicEDT3D)
include_directories(
  ${DYNAMICEDT3D_INCLUDE_DIRS}
)

target_link_libraries(nodename
  ${catkin_LIBRARIES}
  ${OCTOMAP_LIBRARIES}
  ${DYNAMICEDT3D_LIBRARIES}
)
```
