### ISSUE TITLE
octovis make erro:

### ISSUE THREAD

**Issue by wojiaojiao** [OctoMap/octomap#162]
CMakeFiles/octovis.dir/src/ViewerGui.cpp.o：在函数‘octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::updateNodeRecurs(octomap::OcTreeNode*, bool, octomap::OcTreeKey const&, unsigned int, float const&, bool)’中：
ViewerGui.cpp:(.text._ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16updateNodeRecursEPS1_bRKNS_9OcTreeKeyEjRKfb[_ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16updateNodeRecursEPS1_bRKNS_9OcTreeKeyEjRKfb]+0x3ea)：对‘octomap::OcTreeNode::createChild(unsigned int)’未定义的引用
CMakeFiles/octovis.dir/src/ViewerGui.cpp.o：在函数‘octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::readBinaryNode(std::istream&, octomap::OcTreeNode*) const’中：
ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x9e)：对‘octomap::OcTreeNode::createChild(unsigned int)’未定义的引用
ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x11b)：对‘octomap::OcTreeNode::createChild(unsigned int)’未定义的引用
ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x21d)：对‘octomap::OcTreeNode::createChild(unsigned int)’未定义的引用
ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x249)：对‘octomap::OcTreeNode::createChild(unsigned int)’未定义的引用
CMakeFiles/octovis.dir/src/ViewerGui.cpp.o:ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x282): 跟着更多未定义的参考到 octomap::OcTreeNode::createChild(unsigned int)
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/octovis] 错误 1
make[1]: *** [CMakeFiles/octovis.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by ahornung** [comment]
Could you post more details with verbose output, which version, how exactly are you compiling?

Could this be related to https://github.com/OctoMap/octomap/issues/164?

**Comment by wojiaojiao** [comment]
thank,i use https://github.com/ethz-asl/octomap,is not any problem
