### ISSUE TITLE
Generating include/octovis/moc_ViewerGui.cxx error

### ISSUE THREAD

**Issue by ttytt1978** [OctoMap/octomap#164]
I use:make VERBOSE=1 show:
.
.
.
[ 70%] Generating include/octovis/moc_ViewerGui.cxx
cd /home/weijia/下载/octomap/octomap/build/octovis/include/octovis && /usr/lib/x86_64-linux-gnu/qt4/bin/moc @/home/weijia/下载/octomap/octomap/build/octovis/include/octovis/moc_ViewerGui.cxx_parameters
moc: Cannot open options file specified with @
Usage: moc [options] <header-file>
  -o<file>           write output to file rather than stdout
  -I<dir>            add dir to the include path for header files
  -E                 preprocess only; do not generate meta object code
  -D<macro>[=<def>]  define macro, with optional definition
  -U<macro>          undefine macro
  -i                 do not generate an #include statement
  -p<path>           path prefix for included file
  -f[<file>]         force #include, optional file name
  -nn                do not display notes
  -nw                do not display warnings
  @<file>            read additional options from file
  -v                 display version of moc
octovis/CMakeFiles/octovis.dir/build.make:78: recipe for target 'octovis/include/octovis/moc_ViewerGui.cxx' failed
make[2]: *** [octovis/include/octovis/moc_ViewerGui.cxx] Error 1
make[2]: Leaving directory '/home/weijia/下载/octomap/octomap/build'
CMakeFiles/Makefile2:2186: recipe for target 'octovis/CMakeFiles/octovis.dir/all' failed
make[1]: *** [octovis/CMakeFiles/octovis.dir/all] Error 2
make[1]: Leaving directory '/home/weijia/下载/octomap/octomap/build'
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

Why can't I use moc_ViewerGui.cxx_parameters?

**Comment by ahornung** [comment]
Could this be because of the Chinese characters in you path? Could you 
test with a different directory?

**Comment by ttytt1978** [comment]
@ahornung Thank's. I change the directory,it build successful.
