### ISSUE TITLE
Compile error when compile octomap

### ISSUE THREAD

**Issue by xuao0728** [OctoMap/octomap#166]
Recently i compiled octomap, but error occurred like this:

> [ 87%] Building CXX object octovis/CMakeFiles/octovis.dir/qrc_icons.cxx.o
cd /home/aicrobo/kaiyuanku/octomap/build/octovis && /usr/bin/c++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_XML_LIB -Wall -Wno-error  -O3 -funroll-loops -DNDEBUG -isystem /home/aicrobo/kaiyuanku/octomap/octomap/include -I/home/aicrobo/kaiyuanku/octomap/octovis/include -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtOpenGL -isystem /usr/include/qt4/QtGui -isystem /usr/include/qt4/QtXml -isystem /usr/include/qt4/QtCore -I/usr/include/QGLViewer -I/home/aicrobo/kaiyuanku/octomap/build/octovis -I/home/aicrobo/kaiyuanku/octomap/build    -fPIC -o CMakeFiles/octovis.dir/qrc_icons.cxx.o -c /home/aicrobo/kaiyuanku/octomap/build/octovis/qrc_icons.cxx
Linking CXX executable ../../octovis/bin/octovis
cd /home/aicrobo/kaiyuanku/octomap/build/octovis && /usr/bin/cmake -E cmake_link_script CMakeFiles/octovis.dir/link.txt --verbose=1
/usr/bin/c++    -Wall -Wno-error  -O3 -funroll-loops -DNDEBUG    CMakeFiles/octovis.dir/src/main.cpp.o CMakeFiles/octovis.dir/src/ViewerGui.cpp.o CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o CMakeFiles/octovis.dir/src/ViewerSettings.cpp.o CMakeFiles/octovis.dir/src/ViewerSettingsPanel.cpp.o CMakeFiles/octovis.dir/src/ViewerSettingsPanelCamera.cpp.o CMakeFiles/octovis.dir/src/CameraFollowMode.cpp.o CMakeFiles/octovis.dir/include/octovis/moc_ViewerGui.cxx.o CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o CMakeFiles/octovis.dir/include/octovis/moc_ViewerSettings.cxx.o CMakeFiles/octovis.dir/include/octovis/moc_ViewerSettingsPanel.cxx.o CMakeFiles/octovis.dir/include/octovis/moc_ViewerSettingsPanelCamera.cxx.o CMakeFiles/octovis.dir/include/octovis/moc_CameraFollowMode.cxx.o CMakeFiles/octovis.dir/qrc_icons.cxx.o  -o ../../octovis/bin/octovis -rdynamic -lQtOpenGL -lQtGui -lQtXml -lQtCore ../../octomap/lib/liboctomap.so ../../octomap/lib/liboctomath.so ../../octovis/lib/liboctovis.so.1.8.0 -lGL -lGLU ../../octomap/lib/liboctomap.so ../../octomap/lib/liboctomath.so /usr/local/lib/libQGLViewer-qt4.so -Wl,-rpath,/home/aicrobo/kaiyuanku/octomap/octomap/lib:/home/aicrobo/kaiyuanku/octomap/octovis/lib:/usr/local/lib: 
CMakeFiles/octovis.dir/src/ViewerGui.cpp.o: In function `octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::updateNodeRecurs(octomap::OcTreeNode*, bool, octomap::OcTreeKey const&, unsigned int, float const&, bool)':
ViewerGui.cpp:(.text._ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16updateNodeRecursEPS1_bRKNS_9OcTreeKeyEjRKfb[_ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16updateNodeRecursEPS1_bRKNS_9OcTreeKeyEjRKfb]+0x3ea): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
CMakeFiles/octovis.dir/src/ViewerGui.cpp.o: In function `octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::readBinaryNode(std::istream&, octomap::OcTreeNode*) const':
ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x9e): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x11b): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x21d): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x249): undefined reference to `octomap::OcTreeNode::createChild(unsigned int)'
CMakeFiles/octovis.dir/src/ViewerGui.cpp.o:ViewerGui.cpp:(.text._ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_[_ZNK7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE14readBinaryNodeERSiPS1_]+0x282): more undefined references to `octomap::OcTreeNode::createChild(unsigned int)' follow
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::resetView()':
ViewerWidget.cpp:(.text+0x3c9): undefined reference to `qglviewer::Camera::setOrientation(float, float)'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::setCamPosition(double, double, double, double, double, double)':
ViewerWidget.cpp:(.text+0xbc6): undefined reference to `qglviewer::Camera::setOrientation(float, float)'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::jumpToCamFrame(int, int)':
ViewerWidget.cpp:(.text+0xd8c): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::deleteCameraPath(int)':
ViewerWidget.cpp:(.text+0xf70): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
ViewerWidget.cpp:(.text+0xf84): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
ViewerWidget.cpp:(.text+0xfa8): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
ViewerWidget.cpp:(.text+0xfcc): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o:ViewerWidget.cpp:(.text+0x1078): more undefined references to `qglviewer::Camera::keyFrameInterpolator(int) const' follow
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::appendToCameraPath(int, octomath::Pose6D const&)':
ViewerWidget.cpp:(.text+0x10eb): undefined reference to `qglviewer::Camera::setKeyFrameInterpolator(int, qglviewer::KeyFrameInterpolator*)'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::removeFromCameraPath(int, int)':
ViewerWidget.cpp:(.text+0x114d): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
ViewerWidget.cpp:(.text+0x1208): undefined reference to `qglviewer::Camera::setKeyFrameInterpolator(int, qglviewer::KeyFrameInterpolator*)'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::updateCameraPath(int, int)':
ViewerWidget.cpp:(.text+0x127d): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
ViewerWidget.cpp:(.text+0x1340): undefined reference to `qglviewer::Camera::setKeyFrameInterpolator(int, qglviewer::KeyFrameInterpolator*)'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::addCurrentToCameraPath(int, int)':
ViewerWidget.cpp:(.text+0x13ae): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
ViewerWidget.cpp:(.text+0x14c0): undefined reference to `qglviewer::Camera::setKeyFrameInterpolator(int, qglviewer::KeyFrameInterpolator*)'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::appendCurrentToCameraPath(int)':
ViewerWidget.cpp:(.text+0x1520): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
ViewerWidget.cpp:(.text+0x1532): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::playCameraPath(int, int)':
ViewerWidget.cpp:(.text+0x1568): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::stopCameraPath(int)':
ViewerWidget.cpp:(.text+0x1720): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
ViewerWidget.cpp:(.text+0x1734): undefined reference to `qglviewer::Camera::keyFrameInterpolator(int) const'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o:ViewerWidget.cpp:(.text+0x1749): more undefined references to `qglviewer::Camera::keyFrameInterpolator(int) const' follow
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::postDraw()':
ViewerWidget.cpp:(.text+0x1b16): undefined reference to `QGLViewer::drawAxis(float)'
ViewerWidget.cpp:(.text+0x1bcb): undefined reference to `QGLViewer::drawGrid(float, int)'
CMakeFiles/octovis.dir/src/ViewerWidget.cpp.o: In function `octomap::ViewerWidget::draw()':
ViewerWidget.cpp:(.text+0x221): undefined reference to `QGLViewer::setMouseBinding(int, QGLViewer::MouseHandler, QGLViewer::MouseAction, bool)'
CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o: In function `QGLViewer::setSceneRadius(float)':
moc_ViewerWidget.cxx:(.text._ZN9QGLViewer14setSceneRadiusEf[_ZN9QGLViewer14setSceneRadiusEf]+0x5): undefined reference to `qglviewer::Camera::setSceneRadius(float)'
CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o:(.data.rel.ro._ZTVN7octomap12ViewerWidgetE[_ZTVN7octomap12ViewerWidgetE]+0x230): undefined reference to `QGLViewer::drawLight(unsigned int, float) const'
CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o:(.data.rel.ro._ZTVN7octomap12ViewerWidgetE[_ZTVN7octomap12ViewerWidgetE]+0x2e8): undefined reference to `QGLViewer::setKeyFrameKey(int, int)'
CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o:(.data.rel.ro._ZTVN7octomap12ViewerWidgetE[_ZTVN7octomap12ViewerWidgetE]+0x2f0): undefined reference to `QGLViewer::setPlayKeyFramePathStateKey(int)'
CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o:(.data.rel.ro._ZTVN7octomap12ViewerWidgetE[_ZTVN7octomap12ViewerWidgetE]+0x2f8): undefined reference to `QGLViewer::setPlayPathStateKey(int)'
CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o:(.data.rel.ro._ZTVN7octomap12ViewerWidgetE[_ZTVN7octomap12ViewerWidgetE]+0x300): undefined reference to `QGLViewer::setAddKeyFrameStateKey(int)'
CMakeFiles/octovis.dir/include/octovis/moc_ViewerWidget.cxx.o:(.data.rel.ro._ZTVN7octomap12ViewerWidgetE[_ZTVN7octomap12ViewerWidgetE]+0x308): undefined reference to `QGLViewer::setPathKey(int, int)'
../../octovis/lib/liboctovis.so.1.8.0: undefined reference to `QGLViewer::drawArrow(float, float, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [../octovis/bin/octovis] Error 1
make[2]: Leaving directory `/home/aicrobo/kaiyuanku/octomap/build'
make[1]: *** [octovis/CMakeFiles/octovis.dir/all] Error 2
make[1]: Leaving directory `/home/aicrobo/kaiyuanku/octomap/build'
make: *** [all] Error 2

I'm sure i have installed the dependencies `sudo apt-get install libqt4-dev qt4-qmake libqglviewer-dev`,and i don't know what's wrong with it.I'm using ubuntu14.04.

**Comment by ahornung** [comment]
Do you have other versions installed  that could interfere? I'm seeing a `/usr/local/...` path above, I'm pretty sure that's not the apt-get installed version of libqglviewer.

Are you compiling a specific release of OctoMap? Does the behavior change if you use v1.8.1 or the latest version in the `devel` branch instead? (be sure to remove the build directory and CMakeCache)

**Comment by SouthEastleo** [comment]
Hello,I met this problem too,it maybe you has installed the ROS.but what a pity,I still not solve the problem,If you have the solution,please contact me .Thanks.  my e-mail is  luze0625@163.com

**Comment by mayankamedhe** [comment]
Was anyone able to solve this problem? I am trying to compile another program but facing similar situation.

Thanks in advance!

**Comment by mayankamedhe** [comment]
I was able to solve the problem. If anyone else is facing the same problem they can try adding the path of libqglviewer.so in the target link libraries.
