### ISSUE TITLE
About Octomap real time viewer 

### ISSUE THREAD

**Issue by RuPingCen** [OctoMap/octomap#172]
Does Octomap exist for real-time display of the function interface ?  if not ,is there any other way here to achieve this ?

**Comment by gapaluec** [comment]
I too need this feature.

**Comment by ahornung** [comment]
Depending on your definition of "real-time" you can use OctoMap to build maps in real-time. The internal viewer OctoVis does not support some live-display, but you can use the Qt module used internally to build your own visualization.

If you run ROS, you can easily display OctoMaps "live" in RViz using the `octomap_rviz_plugins` package.

**Comment by RuPingCen** [comment]
@ahornung  thank you for your answers.  I am not clear your means. Could you give me some advise how to add the plug to rviz in ROS and which topic should I listen by this way?

**Comment by RuPingCen** [comment]
@gapaluec  I have successfully achieved this function, and I have creat a blog to introduce how to achieved this function. You can find in this website http://blog.csdn.net/crp997576280/article/details/74605766
If you have any trouble with Chinese you can send an email to me.

**Comment by ThadeuVBrito** [comment]
Hello @RuPingCen , I'm trying to develop a system with a UR5 to avoid obstacles, I think octomap can help me. However I could not make octomap work in my work. Could you share your codes? I accessed the blog, but it did not work anyway.

**Comment by RuPingCen** [comment]
@ThadeuVBrito  Sorry, I'm not clear about your problem. I have put the code into the blog, that code aims to load a point cloud file into memory and publish the data to a topic frequently. If you want to fix the code, you need to launch octomap service and config the subscriber topic name of octomap-service.  Finally to subscribe the topic published by octomap-service in rviz plugins. 
If you have trouble in making source code. you need to follow the steps in https://github.com/OctoMap/octomap

**Comment by ThadeuVBrito** [comment]
Thank you for the explanation! I already managed to run octomap_server, your blog codes worked as a guide. Would you know to answer me why the moveit does not recognize as an obstacle?(in my work)
