### ISSUE TITLE
libqglviewer-dev-qt4 package name error in README file

### ISSUE THREAD

**Issue by blup-Blupon** [OctoMap/octomap#173]
Hi,

About that readme [file](https://github.com/OctoMap/octomap/blob/devel/octomap/README.md)
I think the mentioned package name is [libqglviewer-dev-qt4](https://packages.ubuntu.com/xenial/libqglviewer-dev-qt4) and not libqglviewer-qt4-dev.
 

One should probably take that into account to avoid
`E: Unable to locate package libqglviewer-qt4-dev`

Edit: wrong name on the [wiki](https://github.com/OctoMap/octomap/wiki/Compilation-and-Installation-of-OctoMap) as well

-- 
Blupon

**Comment by ahornung** [comment]
That depends on your Ubuntu distro, apparently they decided to change the package name over the course of time:
https://launchpad.net/ubuntu/precise/+package/libqglviewer-qt4-dev

Nevertheless, the instructions should probably reflect the most recent name.

**Comment by blup-Blupon** [comment]
Ok, well thanks ! ;)
