### ISSUE TITLE
OcTree that forgets nodes which haven't been updated for long time

### ISSUE THREAD

**Issue by michael-p** [OctoMap/octomap#174]
_Note: I also asked this question the mailing list but that one seems to be pretty dead, so reposting here_

Dear all,

I'm trying to accomplish something similar to OcTreeStamped: I would like to record for each node the time when it has last been updated (but different to OcTreeStamped it's not system time, i.e. time(NULL), but instead a per-tree counter that I increment manually) and then completely delete nodes that haven't been updated for some amount of time (in contrast to OcTreeStamped which just decrements the occupancy probability for those nodes). One reason for the last difference is that it would keep memory usage low even if the robot travels a very long trajectory.

I tried to adapt OcTreeStamped mostly by just setting the log-odds of "old" nodes to 0.0 and then calling prune() on the tree ([full code](https://gist.github.com/michael-p/ad38e364f55453f6387c260afb93d937)). However, the problem is that when checking in octovis although the map does indeed forget old nodes in that they are not occupied anymore, it does not seem to delete the nodes: when I show the tree structure in octovis the "old" parts of the map still have very fine resolution nodes, and also memory usage as reported by memoryUsage() drops by just a small amount.

So it looks like I'm missing/misunderstanding something fundamental here - I would by happy for any tips on how to do this and what I am missing! Also, I'm open for suggestions if there's a better way to do what I'm trying to do here :)

Thank you very much!
Michael

**Comment by ahornung** [comment]
Answered on the mailing list, closing here. It's not dead, just "slow" :wink:

**Comment by michael-p** [comment]
Thanks, and I apologize for being too "pushy" :)

For future reference, Armin's answer on the mailing list is here: https://groups.google.com/d/msg/octomap/9IHHN2hH64w/D6nPiLzJDAAJ

Best
Michael
