### ISSUE TITLE
octovis fails to build on xenial

### ISSUE THREAD

**Issue by remster** [OctoMap/octomap#179]
cmake ..

-- octovis building as Release
-- Found octomap version: 1.9.0
qmake: could not find a Qt installation of ''
-- Found unsuitable Qt version "" from NOTFOUND
-- QGLViewer includes found in /home/.../Projects/airmap/octomap/octovis/src/extern/QGLViewer
-- QGLViewer library not found.
-- Trying to build libQGLViewer from source in /home/.../Projects/airmap/octomap/octovis/src/extern/QGLViewer
-- 	 generating Makefile using qmake
-- 	 building library (this may take some time...)
make: *** No targets specified and no makefile found. Stop.
CMake Warning at CMakeModules/FindQGLViewer.cmake:107 (MESSAGE):
  Could not find libQGLViewer.so, failed to build?
Call Stack (most recent call first):
  CMakeLists.txt:76 (FIND_PACKAGE)

**Comment by ahornung** [comment]
Please check the error messages above: You're missing Qt4 and QGLViewer.
