### ISSUE TITLE
Creating an OcTree with multiple frames from Kitti for Autonomous Driving

### ISSUE THREAD

**Issue by luigui2906** [OctoMap/octomap#180]
Hello, 

I am exploring Octomaps on Windows as an useful tool for AD, and I am trying to create a map from several frames that I read from Kitti. I am correctly applying the transformation matrices (rotation + translation) to take every frame points to the reference of the first frame and saving them into a Pointcloud, and then using for every frame the insertPointCloud function ( Octree_map.insertPointCloud(frame_pointcloud, sensor_origin) ) giving the frame Pointcloud and the position of the lidar at particular frame. A reconstruction of the total Pointcloud from several frames using PCL can be seen on the following image:

![sans titre1](https://user-images.githubusercontent.com/5257657/28564246-ae42a028-7128-11e7-8e79-7515ee32610f.png)

However, when I do the same for the OcTree, I find a lot of voxels (specially on the floor) that has been marked as free and it shouldn't, I guess this happens because of ray impacts on previous frames where voxels between the sensor origin and the point of impact are marked as free. Is there any way to prevent this..? Is there another function that has to be used if I want to integrate several frames into a single OcTree..? I think the prevention to avoid holes in the floor from mutual deletion is already been done for every frame individually but not when I integrate every frame into the same OcTree. An image of the OcTree after integrating all the frames can be seen: 

![capture2](https://user-images.githubusercontent.com/5257657/28565922-eae2b5e0-712d-11e7-88fa-a286c290fab3.JPG)

Hope I explained myself good enough, thank you for your help and have a nice day.

**Comment by ahornung** [comment]
Yes, that problem is described in detail in the paper, did you have a look at it? You might get lucky by tuning the sensor model parameters, but the best solution will be to combine multiple scan lines into a single point cloud. This requires a  common (virtual?) sensor origin, however.

**Comment by ahornung** [comment]
I'm closing this issue / question due to inactivity.
