### ISSUE TITLE
Octomap not clearing properly

### ISSUE THREAD

**Issue by abhinavrai44** [OctoMap/octomap#183]
When a dynamic obstacle passes in front of another static obstacle, the voxels (of the dynamic obstacle) do not get cleared properly in front the static obstacle and some voxels retain even after the dynamic obstacle is now not present at that position. 

I'm not sure whether there is some problem in the code or some hardware problem.

**Comment by ahornung** [comment]
Is enough of a static background seen behind the disappeared dynamic obstacle?

In some cases it helps to change the map resolution (could be too fine, the clearing rays don't exactly hit the diappeared dynamic obstacle) or change the sensor model parameter (weight of a hit vs. a clearing miss).

**Comment by atzzy** [comment]
I have the same issue. I notice that if there is a static background, the dynamic obstacle does clear partially. However, when there is no static background, the dynamic obstacle does not clear. Is it possible to make the dynamic obstacle clear when there is no static background? 

Where can I change the map resolution and sensor model parameter?

**Comment by nis-ur** [comment]
Hi @abhinavrai44 @ahornung @atzzy , did any of you find a resolution to this? I also now have an octomap which does not clear correctly, meaning that dynamic objects are retained. Thanks!

**Comment by ahornung** [comment]
I'm closing this issue / question due to inactivity.
