### ISSUE TITLE
octomap_msgs to octree

### ISSUE THREAD

**Issue by Annaiyan** [OctoMap/octomap#186]
Hi,

I would like to access the octomap_msgs to get the grid length, width and height. I'm using the function as shown below,
```
 octomap_msgs::Octomap octomap_data(*msg);
 octomap::AbstractOcTree* my_tree = octomap_msgs::binaryMsgToMap(octomap_data)
```

how to get the required data from _my_tree_ ?

**Comment by ahornung** [comment]
That's not an issue but a question for support. Please check the [API documentation](https://octomap.github.io/octomap/doc/), especially accessing the members. You'll have to `dynamic_cast` to the octree type you used before (e.g. octomap::OcTree)
