### ISSUE TITLE
dynamic threshold

### ISSUE THREAD

**Issue by junjie666666** [OctoMap/octomap#193]
I try to have different   threshold for occupancy.
I use the function setOccupancyThres(),change the threshold for several times.
but I view the result by octovis,and find olny the last threshold works.The map has the same last threshold value.
so how to achieve dynamic threshold.
thank you,looking forward your answer.

**Comment by ahornung** [comment]
I don't understand what you mean with "dynamic threshold". There is only one global setting for the occupancy threshold of the whole tree, so only one setting is "preserved".
