### ISSUE TITLE
how to find adjacent nodes in 3D space using octomap

### ISSUE THREAD

**Issue by OsgoodWu** [OctoMap/octomap#196]
I just want to find adjacent free nodes using octomap for navigation, if I just traverse all nodes and pick up all free nodes and then traverse all free nodes to find whether they are adjacent or not according to their distance. I think it's too computing burdened, can anyone tell me a good solution ? I would be very appreciated.

**Comment by ahornung** [comment]
Please check #42 and the comments there. You would have to implement some kind of 3D connectivity analysis (3D connected components), there is nothing like that implemented in OctoMap right now.
