### ISSUE TITLE
Release 1.9.0 for Kinetic

### ISSUE THREAD

**Issue by jvgomez** [OctoMap/octomap#197]
Hi,

Is there any plan to release the version 1.9.0 for Kinetic? That would be nice so that I do not have to rely on a self-build package.

@jpardeiro FYI.

Thanks!

**Comment by ahornung** [comment]
I'm not planning on releasing 1.9 into ROS Kinetic since it's a (potentially) breaking change, e.g. regarding the CMake interface. That could break existing code in an already long-released ROS version.
