### ISSUE TITLE
Is the .bt Octomap preserving the coordinates of the ROS environment it has been built from?

### ISSUE THREAD

**Issue by daniglezad** [OctoMap/octomap#204]
I think the title is self-explicative.
I constructed an Octomap out of a robot moving in a simulated environment. In that environment, the coordinate (x1, y1, z1) with respect to the world frame was occupied by an obstacle.
If I check the node (x1, y1, z1) of the created Octomap, will it be occupied, and if so, by the same obstacle? Or will the Octomap have assigned new coordinates based on the .bt file created?

Also, will it happen the same when the octomap is not in a .bt file and it is being updated continuously?

Thank you.

**Comment by ahornung** [comment]
The .bt format does not compute or change any coordinate transformations, an OctoMap is aways regarded in the same frame. So unless you manually apply a transformation in ROS on top, the coordinates should be the same.

**Comment by daniglezad** [comment]
From your words then I assume that this is not only for .bt octomaps, but for all octomaps.
Thank you.

**Comment by ahornung** [comment]
Yes, that's generally the idea.
