### ISSUE TITLE
Release octomap into Melodic

### ISSUE THREAD

**Issue by clalancette** [OctoMap/octomap#205]
This is a friendly reminder that the Melodic buildfarm is [now available](https://discourse.ros.org/t/melodic-morenia-buildfarm-available/4248). It would be great to have a release of `octomap` into Melodic, as it is currently directly blocking 5 packages and indirectly blocking 14 packages (http://repositories.ros.org/status_page/blocked_releases_melodic.html). Thank you!

**Comment by ahornung** [comment]
Thanks for the reminder! I just triggered a release, should be passing the build farm soon.

**Comment by ahornung** [comment]
@dirk-thomas I'm getting a number of "build failed" messages regularly for OctoMap, any idea what's going on? Looks like Debian is affected with "fatal: Remote branch debian/ros-melodic-octomap_1.9.0-0_stretch not found in upstream origin".

I used bloom-release version 0.5.20.

**Comment by dirk-thomas** [comment]
When I try to invoke a `bloom` release of `octomap` for `melodic` I get the following mesage:

> Your track's 'actions' configuration is not the same as the default.
Unless you have manually modified your 'actions' (the commands which get run for a release), you should update to the new default.
Should it be updated to the default setting?

So it seems that the actions are not update. And looking at the `tracks.yaml` file it doesn't have an action for Debian. So I think updating the actions as bloom suggests should fix the lack of Debian branches / tags in the release repo.

**Comment by ahornung** [comment]
That's weird, I created a new track without any manual changes. I'm not getting the message above either when running bloom-release again. Is there a way to manually reset the track?

**Comment by dirk-thomas** [comment]
> I used bloom-release version 0.5.20.

You might want to try to update your bloom version. Current is 0.6.4.

**Comment by ahornung** [comment]
Ah, I see, thanks. New release on the way with bloom 0.6.4.

0.5.2 was supplied with Ubuntu 16.04, I had assumed it was the latest version.
