### ISSUE TITLE
How to Segment Octree？

### ISSUE THREAD

**Issue by PanZhichen** [OctoMap/octomap#207]
I am doing my path planning task in a large scale outdoor environment.
Suppose I have two ‘octomap::octree’ variables, **oct_temp** and **oct_map**. And the current position of robot in the map is already known : **P=[x,y,z]**.
The global map is stored in **oct_map**, and I want to use **oct_temp** to store a segmentation of global map which contains nodes within 30 meters from position **P** in **oct_map**.
I know the data structure of octree is different from PCL, but I can't extract a specific node of **oct_map** and copy it to **oct_temp**. 
I stuck on this issue for a long time, any suggestion is very big help for me， thanks!

**Comment by ahornung** [comment]
Sorry, but this is not an issue. For general questions, better use the mailing list.
