### ISSUE TITLE
What is the label of an obstacle's inside voxels? 

### ISSUE THREAD

**Issue by zhudelong** [OctoMap/octomap#210]
Anyone knows what the inside voxels of obstacles are labeled? unknown or occupied? 

Secondly, I want to make a confirmation about the origin of the "big cube", is it at the center of the cube? i.e. the range of each dimension is [-2^15*resolution, +2^15*resolution], am I right?

The last question, when a tree is pruned, e.g. the 4th node in 6th depth level, when I query the states of nodes that are the children of this node, the return should be 4th node's state, right? how does the author process such kind of query?

Would anyone give some code patches or examples so that I could save some time? Thanks for your help in advance!

**Comment by ahornung** [comment]
Please use the mailing list for questions and discussions. Thanks!
