### ISSUE TITLE
Let Octomap project to ground and produce 2D probability and height cost map

### ISSUE THREAD

**Issue by bryanibit** [OctoMap/octomap#211]
I have found the octomap_server can produce a topic called /project_map whose type is nav_msgs/OccupancyGrid. But the 2D map have either 1 or 100 free or occupancy, also, -1 for unknown . I want to have a 2D map which has probability and height for each cell in highest resolution 16. Could you please tell me how to project octomap to 2D map? Which function do I need to use? Or how to finish the process. Thank you so much.

**Comment by ahornung** [comment]
There's no such function available. You will have to implement it yourself.

**Comment by bryanibit** [comment]
@ahornung Could you please provide me some detail ideas for this kind of projection. For example, should I use leaf_iterator to iterate the whole octree? Or how to make it based on updating 2D map in octomap_server.
Thank you so much!
