### ISSUE TITLE
Height limit don‘t work

### ISSUE THREAD

**Issue by Zhehua-Hu** [OctoMap/octomap#212]
I play kitti bag and run octomap_server with parameter:
  <node pkg="octomap_server" type="octomap_server_node" name="octomap_server">

    
    <param name="frame_id" type="string" value="/camera_init" />

    
    <param name="resolution" value="0.2" />

    <param name="height_map" value="false" />

    <param name="sensor_model/max_range" value="-1" />
    <param name="latch" value="false" />
    <param name="occupancy_max_z" value="1000" />
    <param name="occupancy_min_z" value="-1000" />
    <param name="pointcloud_max_z" value="1000" />
    <param name="pointcloud_min_z" value="-1000" />
    
	<remap from="cloud_in" to="/kitti/velo/pointclouds" />
  </node>

![selection_002](https://user-images.githubusercontent.com/6281180/41901652-12a9ce1c-7964-11e8-9f89-a6f239d19722.png)

But the point was not showed when it larger than 100m ( The cell grid is 100m and point was is xz plane， so the  octomap was colored by height Z).

Why the max Z was still limited as 100m?

**Comment by SiHeon** [comment]
I have same problem with this one

<launch>
    <node pkg="octomap_server" type="octomap_server_node" name="octomap_server">
        <param name="resolution" value="1" />
        
        
        <param name="frame_id" type="string" value="/odometry" />

                <param name="sensor_model/hit" value="0.7" />
                <param name="sensor_model/miss" value="0.4" />
                <param name="sensor_model/min" value="0.12" />
                <param name="sensor_model/max" value="0.97" />
                <param name="occupancy_min_z" value="-500" />
                <param name="occupancy_max_z" value="500" />

                <param name="publish_free_space" value="true" />
                <param name="filter_ground" value="false" />

        
        <param name="sensor_model/max_range" value="-1" />
        
        
        <remap from="cloud_in" to="/velodyne_points" />
    
    </node>
</launch> 

![question](https://user-images.githubusercontent.com/30979035/42093519-9e66d08c-7be7-11e8-97b5-f9cfdee1faef.png)

This picture shows free space.
My pointcloud data is more than 100 meters high.
However, octomap_server does not seem to update more than 100 meters.
Can you tell me how to fix it?

**Comment by ahornung** [comment]
This sounds like an issue with octomap_server and not OctoMap itself. Please report and track the issue there: https://github.com/OctoMap/octomap_mapping/issues
I can't promise a fix though, this looks like a problem with an artificial bounding box or clipping.

**Comment by hanhan119** [comment]
maybe u can try <param name="sensor_model/max_range" value="5000.0" />  I adjusted this parameter to solve the same problem as you.
