### ISSUE TITLE
OctoMap with monocular camera

### ISSUE THREAD

**Issue by mrgransky** [OctoMap/octomap#217]
Hey,

My question might sound a bit high school (ish) , but I was just wondering if OctoMap could be used with Monocular camera for 3D Mapping,

To be more specific, I am using ORB_SLAM2 framework using Monocular camera to generate map of indoor environment. I could not use gmapping due to the fact that there is not laser_scan topic published in ORB_SLAM2. And honestly, I am not interested in converting my point clouds to laser scans as some kind of reverse engineering solution with pointcloud_to_laserscan package.

Instead I am subscribing to PointCloud2 topic to take advantage of OctoMap for mapping.

The result of OctoMap with monocular ORB_SLAM2, however, is more or less crap since I do not get meaningful representation of walls, edges and so on and so forth in rviz.

Your ideas would be quite helpful,

Cheers

**Comment by haakonelf** [comment]
Check out this https://github.com/Hypha-ROS/hypharos_ardrone_navigation
