### ISSUE TITLE
Any plan to make a new release? (v1.9.1?)

### ISSUE THREAD

**Issue by jlblancoc** [OctoMap/octomap#219]
Hi, 

Not a real issue, just a kind request for a new stable release: 
* there are a few commits already merged to `master` since 1.9.0
* At least these PRs can be merged straight away without fear, IMO: 
  * [x] #213 
  * [x] #206 
  * [x] #202 
* [ ] and probably this one too (but I didn't tested it): #153 

Thanks.

**Comment by ahornung** [comment]
Thanks for the heads-up! I'll try to have a look into it.

**Comment by ahornung** [comment]
v1.9.1 released.

**Comment by jlblancoc** [comment]
Fantastic, thanks! :+1:
