### ISSUE TITLE
Octomap PCL integration

### ISSUE THREAD

**Issue by rfsch** [OctoMap/octomap#221]
Hi 

I would like to use OctoMap to create a voxelgrid preferrably only in the Frustrum of a Velodyne LIDAR mounted to a cars top. 
I would like to create an occupancy grid and based on this proceed to object classification. 

Is this possible with OctoMap ? Can Octomap work with PCL library ? 

Thanks

Rupert

**Comment by hnhpulyb** [comment]
I have the same problem as you. Have you solved it?

**Comment by ahornung** [comment]
I'm closing this issue / question due to inactivity.
