### ISSUE TITLE
404  Not Found [IP: 2605:bc80:3010::134 80]

### ISSUE THREAD

**Issue by shlu2019** [OctoMap/octomap#235]
Hi, I am using Ubuntu 18.04 and trying to install moveit/octomap using the command 
sudo apt install ros-melodic-octomap, but there is error as follows, thanks for helping!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  ros-melodic-octomap
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 190 kB of archives.
After this operation, 1.530 kB of additional disk space will be used.
Err:1 http://packages.ros.org/ros/ubuntu bionic/main amd64 ros-melodic-octomap amd64 1.9.0-1bionic.20190318.184016
  404  Not Found [IP: 2605:bc80:3010::134 80]
E: Failed to fetch http://packages.ros.org/ros/ubuntu/pool/main/r/ros-melodic-octomap/ros-melodic-octomap_1.9.0-1bionic.20190318.184016_amd64.deb  404  Not Found [IP: 2605:bc80:3010::134 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by ahornung** [comment]
Try to run "sudo apt-get update" and installing again, this might be an intermittent issue. If this doesn't work, raise an issue with ROS package management (I don't maintain the package hosting).

**Comment by wxmerkt** [comment]
ROS recently rotated the GPG signing keys. You may have to add the new signing key and remove the old, then run `sudo apt-get update` again.
