### ISSUE TITLE
ubuntu16.04 bin/octovis octomap/share/data/geb079.bt error 

### ISSUE THREAD

**Issue by LiXiaoqiangCN** [OctoMap/octomap#236]
lee@Macbook-Pro:~/app/octomap$ bin/octovis octomap/share/data/geb079.bt
*** Error in `bin/octovis': realloc(): invalid pointer: 0x00007f794cd8c820 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f794b1047e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x85d80)[0x7f794b112d80]
/lib/x86_64-linux-gnu/libc.so.6(realloc+0x22f)[0x7f794b1118ef]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN9QListData7reallocEi+0x1f)[0x7f7945d569cf]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN9QListData6appendEi+0x81)[0x7f7945d56aa1]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x1d6d78)[0x7f7945e22d78]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_Z21qRegisterResourceDataiPKhS0_S0_+0x2e6)[0x7f7945e1eb16]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x7bcc3)[0x7f7945cc7cc3]
/lib64/ld-linux-x86-64.so.2(+0x106ba)[0x7f794dd946ba]
/lib64/ld-linux-x86-64.so.2(+0x107cb)[0x7f794dd947cb]
/lib64/ld-linux-x86-64.so.2(+0xc6a)[0x7f794dd84c6a]
======= Memory map: ========
00400000-00460000 r-xp 00000000 08:01 1313128                            /home/lee/app/octomap/bin/octovis
0065f000-00661000 r--p 0005f000 08:01 1313128                            /home/lee/app/octomap/bin/octovis
00661000-00662000 rw-p 00061000 08:01 1313128                            /home/lee/app/octomap/bin/octovis
01359000-0138b000 rw-p 00000000 00:00 0                                  [heap]
7f793c000000-7f793c021000 rw-p 00000000 00:00 0 
7f793c021000-7f7940000000 ---p 00000000 00:00 0 
7f79425c5000-7f7943e7b000 r-xp 00000000 08:01 3279048                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f7943e7b000-7f794407a000 ---p 018b6000 08:01 3279048                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f794407a000-7f794407b000 r--p 018b5000 08:01 3279048                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f794407b000-7f794407c000 rw-p 018b6000 08:01 3279048                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f794407c000-7f79440a0000 r-xp 00000000 08:01 3285878                    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
7f79440a0000-7f794429f000 ---p 00024000 08:01 3285878                    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
7f794429f000-7f79442a1000 r--p 00023000 08:01 3285878                    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
7f79442a1000-7f79442a2000 rw-p 00025000 08:01 3285878                    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
7f79442a2000-7f7944306000 r-xp 00000000 08:01 3286290                    /usr/lib/x86_64-linux-gnu/libpcre16.so.3.13.2
7f7944306000-7f7944506000 ---p 00064000 08:01 3286290                    /usr/lib/x86_64-linux-gnu/libpcre16.so.3.13.2
7f7944506000-7f7944507000 r--p 00064000 08:01 3286290                    /usr/lib/x86_64-linux-gnu/libpcre16.so.3.13.2
7f7944507000-7f7944508000 rw-p 00065000 08:01 3286290                    /usr/lib/x86_64-linux-gnu/libpcre16.so.3.13.2
7f7944508000-7f7944687000 r-xp 00000000 08:01 3279052                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f7944687000-7f7944887000 ---p 0017f000 08:01 3279052                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f7944887000-7f7944897000 r--p 0017f000 08:01 3279052                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f7944897000-7f7944898000 rw-p 0018f000 08:01 3279052                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f7944898000-7f794489c000 rw-p 00000000 00:00 0 
7f794489c000-7f7944aee000 r-xp 00000000 08:01 3279049                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7f7944aee000-7f7944cee000 ---p 00252000 08:01 3279049                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7f7944cee000-7f7944cfd000 r--p 00252000 08:01 3279049                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7f7944cfd000-7f7944cfe000 rw-p 00261000 08:01 3279049                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7f7944cfe000-7f7944d5a000 r-xp 00000000 08:01 3285966                    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
7f7944d5a000-7f7944f5a000 ---p 0005c000 08:01 3285966                    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
7f7944f5a000-7f7944f5b000 r--p 0005c000 08:01 3285966                    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
7f7944f5b000-7f7944f5c000 rw-p 0005d000 08:01 3285966                    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
7f7944f5c000-7f7944f61000 r-xp 00000000 08:01 3285322                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f7944f61000-7f7945160000 ---p 00005000 08:01 3285322                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f7945160000-7f7945161000 r--p 00004000 08:01 3285322                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f7945161000-7f7945162000 rw-p 00005000 08:01 3285322                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f7945162000-7f7945166000 r-xp 00000000 08:01 3943406                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f7945166000-7f7945365000 ---p 00004000 08:01 3943406                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f7945365000-7f7945366000 r--p 00003000 08:01 3943406                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f7945366000-7f7945367000 rw-p 00004000 08:01 3943406                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f7945367000-7f794536e000 r-xp 00000000 08:01 3285703                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f794536e000-7f794556d000 ---p 00007000 08:01 3285703                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f794556d000-7f794556e000 r--p 00006000 08:01 3285703                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f794556e000-7f794556f000 rw-p 00007000 08:01 3285703                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f794556f000-7f79455dd000 r-xp 00000000 08:01 3936909                    /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f79455dd000-7f79457dd000 ---p 0006e000 08:01 3936909                    /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f79457dd000-7f79457de000 r--p 0006e000 08:01 3936909                    /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f79457de000-7f79457df000 rw-p 0006f000 08:01 3936909                    /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f79457df000-7f79457e1000 r-xp 00000000 08:01 3285311                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f79457e1000-7f79459e1000 ---p 00002000 08:01 3285311                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f79459e1000-7f79459e2000 r--p 00002000 08:01 3285311                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f79459e2000-7f79459e3000 rw-p 00003000 08:01 3285311                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f79459e3000-7f7945a45000 r-xp 00000000 08:01 3285350                    /usr/lib/x86_64-linux-gnu/libXt.so.6.0.0
7f7945a45000-7f7945c45000 ---p 00062000 08:01 3285350                    /usr/lib/x86_64-linux-gnu/libXt.so.6.0.0
7f7945c45000-7f7945c46000 r--p 00062000 08:01 3285350                    /usr/lib/x86_64-linux-gnu/libXt.so.6.0.0
7f7945c46000-7f7945c4b000 rw-p 00063000 08:01 3285350                    /usr/lib/x86_64-linux-gnu/libXt.so.6.0.0
7f7945c4b000-7f7945c4c000 rw-p 00000000 00:00 0 
7f7945c4c000-7f7946111000 r-xp 00000000 08:01 3279255                    /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1
7f7946111000-7f794611d000 r--p 004c4000 08:01 3279255                    /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1
7f794611d000-7f794611e000 rw-p 004d0000 08:01 3279255                    /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1
7f794611e000-7f7946122000 rw-p 00000000 00:00 0 
7f7946122000-7f7946649000 r-xp 00000000 08:01 3279266                    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.5.1
7f7946649000-7f794664a000 ---p 00527000 08:01 3279266                    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.5.1
7f794664a000-7f794665f000 r--p 00527000 08:01 3279266                    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.5.1
7f794665f000-7f7946665000 rw-p 0053c000 08:01 3279266                    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.5.1
7f7946665000-7f794666a000 rw-p 00000000 00:00 0 
7f794666a000-7f7946cc3000 r-xp 00000000 08:01 3279268                    /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.5.1
7f7946cc3000-7f7946cf1000 r--p 00658000 08:01 3279268                    /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.5.1
7f7946cf1000-7f7946cf6000 rw-p 00686000 08:01 3279268                    /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.5.1
7f7946cf6000-7f7946cf7000 rw-p 00000000 00:00 0 
7f7946cf7000-7f7946d07000 r-xp 00000000 08:01 3279002                    /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
7f7946d07000-7f7946f07000 ---p 00010000 08:01 3279002                    /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
7f7946f07000-7f7946f08000 r--p 00010000 08:01 3279002                    /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
7f7946f08000-7f7946f09000 rw-p 00011000 08:01 3279002                    /usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
7f7946f09000-7f7946f0e000 r-xp 00000000 08:01 3285362                    /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
7f7946f0e000-7f794710d000 ---p 00005000 08:01 3285362                    /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
7f794710d000-7f794710e000 r--p 00004000 08:01 3285362                    /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
7f794710e000-7f794710f000 rw-p 00005000 08:01 3285362                    /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
7f794710f000-7f7947130000 r-xp 00000000 08:01 3286733                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f7947130000-7f794732f000 ---p 00021000 08:01 3286733                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f794732f000-7f7947330000 r--p 00020000 08:01 3286733                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f7947330000-7f7947331000 rw-p 00021000 08:01 3286733                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f7947331000-7f7947335000 r-xp 00000000 08:01 3286701                    /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
7f7947335000-7f7947534000 ---p 00004000 08:01 3286701                    /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
7f7947534000-7f7947535000 r--p 00003000 08:01 3286701                    /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
7f7947535000-7f7947536000 rw-p 00004000 08:01 3286701                    /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
7f7947536000-7f794754d000 r-xp 00000000 08:01 3286705                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f794754d000-7f794774c000 ---p 00017000 08:01 3286705                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f794774c000-7f794774e000 r--p 00016000 08:01 3286705                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f794774e000-7f794774f000 rw-p 00018000 08:01 3286705                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f794774f000-7f7947750000 r-xp 00000000 08:01 3279012                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f7947750000-7f794794f000 ---p 00001000 08:01 3279012                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f794794f000-7f7947950000 r--p 00000000 08:01 3279012                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f7947950000-7f7947951000 rw-p 00001000 08:01 3279012                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f7947951000-7f7947956000 r-xp 00000000 08:01 3285326                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f7947956000-7f7947b55000 ---p 00005000 08:01 3285326                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f7947b55000-7f7947b56000 r--p 00004000 08:01 3285326                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f7947b56000-7f7947b57000 rw-p 00005000 08:01 3285326                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f7947b57000-7f7947b59000 r-xp 00000000 08:01 3285320                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f7947b59000-7f7947d58000 ---p 00002000 08:01 3285320                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f7947d58000-7f7947d59000 r--p 00001000 08:01 3285320                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f7947d59000-7f7947d5a000 rw-p 00002000 08:01 3285320                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f7947d5a000-7f7947d86000 r-xp 00000000 08:01 3279006                    /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
7f7947d86000-7f7947f85000 ---p 0002c000 08:01 3279006                    /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
7f7947f85000-7f7947f89000 r--p 0002b000 08:01 3279006                    /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
7f7947f89000-7f7947f8a000 rw-p 0002f000 08:01 3279006                    /usr/lib/x86_64-linux-gnu/libglapi.so.0.0.0
7f7947f8a000-7f7947f8b000 rw-p 00000000 00:00 0 
7f7947f8b000-7f7947f8c000 r-xp 00000000 08:01 3286745                    /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
7f7947f8c000-7f794818c000 ---p 00001000 08:01 3286745                    /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
7f794818c000-7f794818d000 r--p 00001000 08:01 3286745                    /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
7f794818d000-7f794818e000 rw-p 00002000 08:01 3286745                    /usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
7f794818e000-7f7948193000 r-xp 00000000 08:01 3286725                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f7948193000-7f7948393000 ---p 00005000 08:01 3286725                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f7948393000-7f7948394000 r--p 00005000 08:01 3286725                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f7948394000-7f7948395000 rw-p 00006000 08:01 3286725                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f7948395000-7f7948397000 r-xp 00000000 08:01 3286713                    /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
7f7948397000-7f7948596000 ---p 00002000 08:01 3286713                    /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
7f7948596000-7f7948597000 r--p 00001000 08:01 3286713                    /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
7f7948597000-7f7948598000 rw-p 00002000 08:01 3286713                    /usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
7f7948598000-7f794859a000 r-xp 00000000 08:01 3286703                    /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
7f794859a000-7f7948799000 ---p 00002000 08:01 3286703                    /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
7f7948799000-7f794879a000 r--p 00001000 08:01 3286703                    /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
7f794879a000-7f794879b000 rw-p 00002000 08:01 3286703                    /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
7f794879b000-7f79487c1000 r-xp 00000000 08:01 3936811                    /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f79487c1000-7f79489c1000 ---p 00026000 08:01 3936811                    /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f79489c1000-7f79489c3000 r--p 00026000 08:01 3936811                    /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f79489c3000-7f79489c4000 rw-p 00028000 08:01 3936811                    /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f79489c4000-7f7948a31000 r-xp 00000000 08:01 3285164                    /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
7f7948a31000-7f7948c31000 ---p 0006d000 08:01 3285164                    /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
7f7948c31000-7f7948c32000 r--p 0006d000 08:01 3285164                    /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
7f7948c32000-7f7948c33000 rw-p 0006e000 08:01 3285164                    /usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
7f7948c33000-7f7948c3a000 r-xp 00000000 08:01 3936934                    /lib/x86_64-linux-gnu/librt-2.23.so
7f7948c3a000-7f7948e39000 ---p 00007000 08:01 3936934                    /lib/x86_64-linux-gnu/librt-2.23.so
7f7948e39000-7f7948e3a000 r--p 00006000 08:01 3936934                    /lib/x86_64-linux-gnu/librt-2.23.so
7f7948e3a000-7f7948e3b000 rw-p 00007000 08:01 3936934                    /lib/x86_64-linux-gnu/librt-2.23.so
7f7948e3b000-7f7948e4c000 r-xp 00000000 08:01 3285324                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f7948e4c000-7f794904b000 ---p 00011000 08:01 3285324                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f794904b000-7f794904c000 r--p 00010000 08:01 3285324                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f794904c000-7f794904d000 rw-p 00011000 08:01 3285324                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f794904d000-7f794905c000 r-xp 00000000 08:01 3285334                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f794905c000-7f794925b000 ---p 0000f000 08:01 3285334                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f794925b000-7f794925c000 r--p 0000e000 08:01 3285334                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f794925c000-7f794925d000 rw-p 0000f000 08:01 3285334                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f794925d000-7f7949273000 r-xp 00000000 08:01 3285172                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f7949273000-7f7949472000 ---p 00016000 08:01 3285172                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f7949472000-7f7949473000 r--p 00015000 08:01 3285172                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f7949473000-7f7949474000 rw-p 00016000 08:01 3285172                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f7949474000-7f7949477000 rw-p 00000000 00:00 0 
7f7949477000-7f794947e000 r-xp 00000000 08:01 3285297                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f794947e000-7f794967d000 ---p 00007000 08:01 3285297                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f794967d000-7f794967e000 r--p 00006000 08:01 3285297                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f794967e000-7f794967f000 rw-p 00007000 08:01 3285297                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f794967f000-7f79496d1000 r-xp 00000000 08:01 3278311                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
7f79496d1000-7f79498d0000 ---p 00052000 08:01 3278311                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
7f79498d0000-7f79498d1000 r--p 00051000 08:01 3278311                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
7f79498d1000-7f79498d2000 rw-p 00052000 08:01 3278311                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
7f79498d2000-7f79498eb000 r-xp 00000000 08:01 3936971                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f79498eb000-7f7949aea000 ---p 00019000 08:01 3936971                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f7949aea000-7f7949aeb000 r--p 00018000 08:01 3936971                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f7949aeb000-7f7949aec000 rw-p 00019000 08:01 3936971                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f7949aec000-7f7949b10000 r-xp 00000000 08:01 3942005                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f7949b10000-7f7949d0f000 ---p 00024000 08:01 3942005                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f7949d0f000-7f7949d10000 r--p 00023000 08:01 3942005                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f7949d10000-7f7949d11000 rw-p 00024000 08:01 3942005                    /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f7949d11000-7f7949e20000 r-xp 00000000 08:01 3943477                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
7f7949e20000-7f794a01f000 ---p 0010f000 08:01 3943477                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
7f794a01f000-7f794a020000 r--p 0010e000 08:01 3943477                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
7f794a020000-7f794a021000 rw-p 0010f000 08:01 3943477                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
7f794a021000-7f794a022000 rw-p 00000000 00:00 0 
7f794a022000-7f794a039000 r-xp 00000000 08:01 3285427                    /usr/lib/x86_64-linux-gnu/libaudio.so.2.4
7f794a039000-7f794a239000 ---p 00017000 08:01 3285427                    /usr/lib/x86_64-linux-gnu/libaudio.so.2.4
7f794a239000-7f794a23a000 r--p 00017000 08:01 3285427                    /usr/lib/x86_64-linux-gnu/libaudio.so.2.4
7f794a23a000-7f794a23b000 rw-p 00018000 08:01 3285427                    /usr/lib/x86_64-linux-gnu/libaudio.so.2.4
7f794a23b000-7f794a253000 r-xp 00000000 08:01 3936926                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f794a253000-7f794a452000 ---p 00018000 08:01 3936926                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f794a452000-7f794a453000 r--p 00017000 08:01 3936926                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f794a453000-7f794a454000 rw-p 00018000 08:01 3936926                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7f794a454000-7f794a458000 rw-p 00000000 00:00 0 
7f794a458000-7f794a495000 r-xp 00000000 08:01 3285717                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f794a495000-7f794a694000 ---p 0003d000 08:01 3285717                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f794a694000-7f794a696000 r--p 0003c000 08:01 3285717                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f794a696000-7f794a69b000 rw-p 0003e000 08:01 3285717                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f794a69b000-7f794a7d0000 r-xp 00000000 08:01 3279010                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f794a7d0000-7f794a9d0000 ---p 00135000 08:01 3279010                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f794a9d0000-7f794a9d1000 r--p 00135000 08:01 3279010                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f794a9d1000-7f794a9d5000 rw-p 00136000 08:01 3279010                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f794a9d5000-7f794a9de000 r-xp 00000000 08:01 3285346                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f794a9de000-7f794abdd000 ---p 00009000 08:01 3285346                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f794abdd000-7f794abde000 r--p 00008000 08:01 3285346                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f794abde000-7f794abdf000 rw-p 00009000 08:01 3285346                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f794abdf000-7f794abe2000 r-xp 00000000 08:01 3936804                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f794abe2000-7f794ade1000 ---p 00003000 08:01 3936804                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f794ade1000-7f794ade2000 r--p 00002000 08:01 3936804                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f794ade2000-7f794ade3000 rw-p 00003000 08:01 3936804                    /lib/x86_64-linux-gnu/libdl-2.23.so
7f794ade3000-7f794ae87000 r-xp 00000000 08:01 3285751                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f794ae87000-7f794b086000 ---p 000a4000 08:01 3285751                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f794b086000-7f794b08c000 r--p 000a3000 08:01 3285751                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f794b08c000-7f794b08d000 rw-p 000a9000 08:01 3285751                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f794b08d000-7f794b24d000 r-xp 00000000 08:01 3936780                    /lib/x86_64-linux-gnu/libc-2.23.so
7f794b24d000-7f794b44d000 ---p 001c0000 08:01 3936780                    /lib/x86_64-linux-gnu/libc-2.23.so
7f794b44d000-7f794b451000 r--p 001c0000 08:01 3936780                    /lib/x86_64-linux-gnu/libc-2.23.so
7f794b451000-7f794b453000 rw-p 001c4000 08:01 3936780                    /lib/x86_64-linux-gnu/libc-2.23.so
7f794b453000-7f794b457000 rw-p 00000000 00:00 0 
7f794b457000-7f794b46d000 r-xp 00000000 08:01 3936818                    /lib/x86_64-linux-gnu/libgcc_s.so.1已放弃 (核心已转储)

**Comment by LiXiaoqiangCN** [comment]
cd octomap
mkdir build
cd build
cmake ..
make

**Comment by ahornung** [comment]
Is this with a clean checkout? Which version of OctoMap did you check out?

**Comment by lukelu0520** [comment]
Hi ahornung,

I also got an error message **Segmentation fault (core dumped)** by running bin/octovis
Since the compile is successful, I was wondering if you have any advice on the error.

**Comment by ahornung** [comment]
OK, thanks for the feedback. I'm closing here.
