### ISSUE TITLE
Add octomap to dashing rosdistro

### ISSUE THREAD

**Issue by anasarrak** [OctoMap/octomap#237]
After the last merged PR https://github.com/OctoMap/octomap/pull/234, we have a compilable version of ROS2 for octomap, allocated on the [ros2 branch](https://github.com/OctoMap/octomap/tree/ros2). Can we create a version for [rosdistro](https://github.com/ros/rosdistro/blob/master/dashing/distribution.yaml)?

**Comment by ahornung** [comment]
@wxmerkt, is ROS/ROS2 maintenance of octomap also something that you would be interested in and could take over?

**Comment by wxmerkt** [comment]
I am happy to make the bloom-release - but currently until mid-September would not have time to address build issues (and instead revert and attempt again at a later stage).

**Comment by rhaschke** [comment]
@wxmerkt, could you please prepare a dashing release on short time scale?
I suggest to discard the changes in #234. As an external cmake-only project, there is no need to introduce ament-related commands. IMHO, the only useful changes in #234 are the format updates to package.xml merging `build_depend` and `run_depend` into `depend` tags.
I think, we can simply release the existing release 1.9 into dashing w/o any changes.

If you don't have time, I can trigger a release as well.

**Comment by wxmerkt** [comment]
Yes, I am happy to also make a release of v1.9 to dashing in the same form it is in melodic.

@rhaschke, thank you for the comment regarding #234. After learning more about the buildsystem differences and our recent conversation, I am fully onboard with your comment. I will make a release of the existing 1.9 tag and take the formatting updates in consideration for a patch release in the future.

**Comment by wxmerkt** [comment]
We first need to merge #263 before being able to make a Dashing release. The existing package.xml depend on `catkin` (albeit it not being required), which does not resolve on ROS2. Te changes in #263 should work on both ROS1 and ROS2. Perhaps we should delete/deprecate the `ros2` branch after the release.

@ahornung Can you please have a look at and merge #263 and indicate whether it's okay for you if I go ahead and make a new patch release 1.9.1 with the latest updates in devel and #263? I don't have permissions on octomap yet - can you please make the release or I am also happy to help with maintaining OctoMap for releases. However, I will be unable to comment on the issues or evaluate the deeper impact of some of the pull requests.

Many thanks :-)

**Comment by ahornung** [comment]
Sorry for the delay, I just came back from a short vacation. OctoMap version 1.9.1 is out, could you take care of the ROS release(s) @wxmerkt ? Thanks!

**Comment by wxmerkt** [comment]
Hope you had a great vacation :-)

Thank you for merging. The releases are out:

- Melodic: https://github.com/ros/rosdistro/pull/23138
- Dashing: https://github.com/ros/rosdistro/pull/23139

**Comment by rhaschke** [comment]
@wxmerkt, thanks for preparing the releases. Could you prepare the same release for Eloquent as well? Thanks.

**Comment by wxmerkt** [comment]
Yes, @rhaschke will do. We currently have one failure on armhf on dashing. I don't have an immediate fix for it, though.

- Eloquent release: https://github.com/ros/rosdistro/pull/23250

**Comment by rhaschke** [comment]
Thanks. Regarding the failure on armhf: Obviously octovis is missing libqglviewer-dev-qt4.
To be honest, I think this should be updated to Qt5 - [Qt4 is eol since Dec 2015](https://www.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year).
Alternatively, consider disabling octovis for arm.

**Comment by wxmerkt** [comment]
Thank you, happy to blacklist octovis for arm. I have never done a blacklist for a package for a platform before - if you have any pointers, I'd highly appreciate it :-)
