### ISSUE TITLE
Input the color_octomap server all red color points cloud but gernerated some white color cubes

### ISSUE THREAD

**Issue by SladeLu** [OctoMap/octomap#239]
1. I has defined the color octomap on octomap_server.h.
2. I turn on the rviz and switch the color channel to cell color.
3. A all red(for test) point cloud was input into the octomap server correclty.
4. The rviz shows the new colorfull octomap has the cubes with red color ALSO with WHITE COLOR

So my question is how to make these white color cubes with the same point cloud color i have put in? I do some trying on octomap_server.cpp and has no ideas. Thanks. 
![TIM截图20190716204632](https://user-images.githubusercontent.com/17822960/61295552-df3d8100-a80a-11e9-8c95-b0419648183a.png)

**Comment by ahornung** [comment]
This sounds like a problem / question related to the ROS integration of OctoMap, not the core OctoMap library. So either use https://github.com/OctoMap/octomap_mapping or https://github.com/OctoMap/octomap_rviz_plugins
