### ISSUE TITLE
is there a prebuilt octovis available for Windows 

### ISSUE THREAD

**Issue by qingli2028** [OctoMap/octomap#241]
I could build or install octovis on Ubuntu. but I have some problem with building octovis under windows 10 with qt 4.8.7. 
I just wonder is there a prebuilt octovis available for Windows? where can I download it? many thanks!

**Comment by ahornung** [comment]
Yes, compiling with various external dependencies is much more painful under Windows than Linux. To my knowledge there is no prebuilt octovis available for Windows.
