### ISSUE TITLE
why octovis can only open .ot files less than 500M bytes?

### ISSUE THREAD

**Issue by qingli2028** [OctoMap/octomap#242]
why octovis under ubuntu can only open .ot files less than 500M bytes? when opening .ot files larger than 500M bytes, it will failed with segmentation fault. it also seems not related with RAM size.

**Comment by ahornung** [comment]
This is related to your installed RAM, octovis most likely crashed because it couldn't allocated more memory.

The 500 MB .ot file is serialized, the octree in memory is larger (check the paper). But significantly larger is the memory requirement for visualization: every voxel is generated in memory to be displayed, occupied and free. This could easily be 8 GB and more for your large file.

**Comment by qingli2028** [comment]
Dear Armin,Thanks a lot for your reply and explanation!It's highly appreciated.I know that to construct the octotree in RAM could need much more ram so we use Ubuntu 16.04 with 32GB of ram, but it's still crashed. we also tried to create/increase the swap partition but also no help.So do you know why? could it because the Ram is enough to construct the octotree but crash when rendering&display?Thanks a lot!Best Regards, Owen-------- 原始邮件 --------主题：Re: [OctoMap/octomap] why octovis can only open .ot files less than 500M bytes? (#242)发件人：Armin Hornung 收件人：OctoMap/octomap 抄送：qingli2028 ,Author This is related to your installed RAM, octovis most likely crashed because it couldn't allocated more memory.
The 500 MB .ot file is serialized, the octree in memory is larger (check the paper). But significantly larger is the memory requirement for visualization: every voxel is generated in memory to be displayed, occupied and free. This could easily be 8 GB and more for your large file.

**Comment by ahornung** [comment]
> could it because the Ram is enough to construct the octotree but crash when rendering&display?

Yes, this is most likely the case. You could try to increase the display voxel size ("depth cutoff"), or try to use a coarser resolution in your octree.

**Comment by qingli2028** [comment]
Dear Armin,OK, got it. Thank you very much! :)Best Regards, Owen-------- 原始邮件 --------主题：Re: [OctoMap/octomap] why octovis can only open .ot files less than 500M bytes? (#242)发件人：Armin Hornung 收件人：OctoMap/octomap 抄送：qingli2028 ,Author 
could it because the Ram is enough to construct the octotree but crash when rendering&display?

Yes, this is most likely the case. You could try to increase the display voxel size ("depth cutoff"), or try to use a coarser resolution in your octree.
