### ISSUE TITLE
How to filter the input point cloud before generating octomap?

### ISSUE THREAD

**Issue by hana9090** [OctoMap/octomap#245]
Hi there,
I need to filter specific point clouds before generating octomap. So what I know that octomap subscribe to the assigned point cloud in the launch file:
`<remap from="cloud_in" to="/radar/points" />`

So in which place in the source code do octomap receive these `cloud_in`, so I can put filter there?

**Comment by wxmerkt** [comment]
Hi @hana9090,
This issue belongs to the [`octomap_ros`](https://github.com/OctoMap/octomap_mapping/) package and not the library in general. 

Please have a look at the [documentation](http://wiki.ros.org/octomap_server) for a list of the configurable filter options. A good way to configure it is to use `rqt_reconfigure` to test suitable values. Alternatively, you can use the filter chains on the raw points and remap `cloud_in` to the filtered topic.
