### ISSUE TITLE
Does Octovis have apis that I can use in other projects?

### ISSUE THREAD

**Issue by bharadwajakshay** [OctoMap/octomap#251]
Hey,
I want to use octovis to visualize my octree / pointclouds / vectors (arrows) etc, in my own project. Is there a way to use this like a library? Is there any documentation regarding the available APIs. I really wanna use octovis to visualize the octree and pointclouds. 
Thanks

**Comment by ahornung** [comment]
There is no explicit API documentation, but you can have a look at the headers and documentation in octovis. It should be extensible pretty easily and can be used as a library.

**Comment by sgolodetz** [comment]
@spacemanspiff0211 For what it's worth, I've been trying to pybind some relevant bits of Octovis today, and can confirm that it's not too tricky to get it working - e.g. take a look at `OcTreeDrawer`. For pybind, this was working for me:

    py::class_<octomap::OcTreeDrawer>(m, "OcTreeDrawer")
      .def(py::init<>(), py::call_guard<py::gil_scoped_release>())
      .def("draw", &octomap::OcTreeDrawer::draw, py::call_guard<py::gil_scoped_release>())
      .def(
        "enable_freespace",
        &octomap::OcTreeDrawer::enableFreespace,
        py::arg("enabled") = true,
        py::call_guard<py::gil_scoped_release>()
      )
      .def("set_color_mode", &octomap::OcTreeDrawer::setColorMode, py::call_guard<py::gil_scoped_release>())
      .def(
        "set_octree",
        [](octomap::OcTreeDrawer& self, const octomap::OcTree& octree, const octomap::pose6d& origin, int map_id_)
        {
          self.setOcTree(octree, origin, map_id_);
        },
        py::arg("octree"), py::arg("origin"), py::arg("map_id_") = 0,
        py::call_guard<py::gil_scoped_release>()
      )
    ;

And then you can just do things like:

    tree: OcTree = OcTree(voxel_size)
    ....
    drawer: OcTreeDrawer = OcTreeDrawer()
    drawer.enable_freespace()
    drawer.set_color_mode(CM_COLOR_HEIGHT)
    ...
    drawer.set_octree(tree, origin_pose)
    ...
    drawer.draw()
