### ISSUE TITLE
getChild() is not a member of octomap...

### ISSUE THREAD

**Issue by thezest76** [OctoMap/octomap#252]
Thanks for the nice SW.

I am trying to run a Motion Planning SW that is dependent on OCTOMAP. Unfortunately, when I tried to run the SW, I get the following error message.

 MyOcTree.h:60:48: error: ‘getChild’ is not a member of ‘octomap::OcTreeNode’
       return static_cast<const MyOcTreeNode*> (OcTreeNode::getChild(i));

I seems to me that OcTreeNode::getChild() was in v1.7.1, but this method is no longer available in the latest stable version

In OcTreeNode.h, I found the following comments 

   * Note: If you derive a class (directly or indirectly) from OcTreeDataNode, 
   * you have to implement (at least) the following functions to avoid slicing
   * errors and memory-related bugs:
   * createChild(), getChild(), getChild() const, expandNode() 
   * See ColorOcTreeNode in ColorOcTree.h for an example. 

However, I wasn't able to locate these implementations in ColorOcTree.h. Is there anyway to resolve this issue ?

Thanks

**Comment by ahornung** [comment]
There was a breaking API change in v1.8.0, please check the [Changelog](https://github.com/OctoMap/octomap/blob/devel/octomap/CHANGELOG.txt).
