### ISSUE TITLE
Viewing with Octovis for merge/split octree tile

### ISSUE THREAD

**Issue by owang-invn** [OctoMap/octomap#253]
Dear Authers,

First of all, sorry to bother.

I have a problem with Octomap library and Octovis as follows, hoping could get some help from you  guys. Thanks in advance!

My target is to merge some .ot tiles (colored tree) into one and then split it into some tiles with our specific requirement.
It seems good with the merging and splitting, the split tiles also works fine as expected, but I do have one split tile which seems not working very well. 
When viewing this tile with Octovis, it look kinda weird on Z-axis as the attached snapshot shows and part of the tile also with wrong color. And this is only wrong with depth of 16, and when I open with depth 14 or 15, everything look good. And all other tiles also looks good. And when I merge all the split tiles back to one tile, it also looks good.
But when I read this tile into memory and dump octree information, it looks good as expected (as show below). And when I convert the color tree to non-color tree, problem still there. But when I convert the tree into .bt file, it works fine.
Besides, I also checked the coordinate of each voxel, all of them are within the tile range/boundingbox specified by metric min/max of this tile.

So any chance you guys has the similar problem before or any suggestion? Many thanks!

Dump information...
tree depth is 16
tree resolution is 0.05
tree occupy threshold is 0.5
tree probability threshold is 0: 0.5
tree nodes num is 35678955
tree leaf nodes num is 24056091
tree size num is 35678955
tree memory usage is 1314726896
tree memory usage node is 16
tree memory full grid is 98121340152
tree volume is 3.06629e+06
tree metric size is: 204.7,313.05,47.85
tree metric min is: -194.5,-58.85,1005.55
tree metric max is: 10.2,254.2,1053.4
tree node size is:, 0: 3276.8, 1: 1638.4, 2: 819.2, 3: 409.6, 4: 204.8, 5: 102.4, 6: 51.2, 7: 25.6, 8: 12.8, 9: 6.4, 10: 3.2, 11: 1.6, 12: 0.8, 13: 0.4, 14: 0.2, 15: 0.1, 16: 0.05
Done with information dump

![Snapshot_ProblemTile1](https://user-images.githubusercontent.com/45612608/66004674-976fe280-e466-11e9-9adf-85e5b2a8b088.PNG)
![Snapshot_ProblemTile2](https://user-images.githubusercontent.com/45612608/66004677-9a6ad300-e466-11e9-89e3-10dd1f8c999d.PNG)

**Comment by owang-invn** [comment]
One more info to provide:

It seems this issue happens when the BBX min point3d is within a small area (20cm*20cm), but if the  BBX min point3d is outside of this small area, it seems ok with Octovis.
So what’s special for BBX min?
BTW, what does this gray triangle means in Octovis? I’ve checked all the leaf nodes of the split .ot file and they are all within metric range. So what is that gray triangle in Octovis means? Many thanks! 
![Snapshot_ProblemTile](https://user-images.githubusercontent.com/45612608/66165818-d6cb3a00-e5f2-11e9-85df-5b44905f7714.PNG)

**Comment by ahornung** [comment]
It looks like the octree is corrupted, either in memory or on disk due to some erroneous update. There should not be any grey or colored triangles, that looks like an error in the display mesh.

**Comment by owang-invn** [comment]
Dear Armin,

Ok, got it. But the problem is that I can’t see any problem when reading this .ot file into memory and constructing the octree in memory. I could also dump its info as I wrote above. And when I did comparison using the building compare tool, they also shows that they are the same between the one before split&merge and the one after split&merge. 

By the way, I also compared using beyond compare the 2 .ot files, the one before split&merge and the one after split&merge, they are totally the same. So if there is some problem with the split .ot, how come after merging back to one .ot file, it’s totally the same with the one before split/merge?

BTW, have you seen this weird triangle before? And what’s the cause then? Many thanks! :)

Best Regards,
Owen

**Comment by owang-invn** [comment]
BTW, BTW, what does this gray and colored triangle means in Octovis? Thanks a lot!

**Comment by ahornung** [comment]
It shouldn't even be there, and I have never seen it before. Do you have sample code on how you create and process the octrees? There's no split and merge functionalty in OctoMap, so I guess it's your own custom implementation?

**Comment by ahornung** [comment]
I'm closing this issue / question due to inactivity.
