### ISSUE TITLE
Can we deem 2 octrees the same?

### ISSUE THREAD

**Issue by owang-invn** [OctoMap/octomap#254]
Dear Author,

I have a question regarding the identity of 2 octree trees.
If 2 octree trees has the exact same number of leaf nodes, and occupancy status, or in other words, they are the same with running the build in tool compare_octrees, but they are with different inner nodes number, could we deem them as the same octrees? 
By the way, I think why the above status happens is like convert one octree to another, but with different root position, so the inner nodes could be different but with the same leaf nodes. 
Many thanks!

BR,
Owen

**Comment by ahornung** [comment]
How did you create these octrees? If the leaf nodes are exactly the same then the inner nodes also need to be identical.

I don't know how you "convert" between different octrees, but a different root position usually also leads to different leaf nodes.

**Comment by owang-invn** [comment]
Dear Armin,

Ok, got it. I guess I already know the answer. Thanks a lot for your explanation! :)

Best Regards,
Owen
