### ISSUE TITLE
Segmentation fault when running octovis

### ISSUE THREAD

**Issue by pxl-accname** [OctoMap/octomap#256]
Hello there,

I cloned the repository and followed the install instructions.
Everything works (cmake, make, make tests). During the build process I never got an error, only a warning which appeared three times during the build process:

"CMake Warning at dynamicEDT3D/CMakeLists.txt:85 (export):
  Cannot create package registry file:

    /home/accname/.cmake/packages/octomap/e770c54deeee3189cf9c7893e5fce109
    /home/accname/.cmake/packages/octovis/e9cfee95a51f61532648959a5e43ae15
    /home/accname/.cmake/packages/dynamicEDT3D/18c4e1cfee0e967064bd577419d96a8a

  Permission denied"

The warning message is always the same, only the path changes. I copied all three occurring warnings into one and kept the order they appeared (the paths).
Has anyone else experience this?

After building everything I am trying to to use the binary file in bin/octovis and try to load the scan.dat. Then I get the following information:

"Loading ASCII pointcloud from file scan.dat...loadGraph:: generating octree from complete graph.
Generating OcTree... 
generateOctree:: inserting scan node with 88206 points, origin: 0,00  ,0,00 , 0,00.
 S (1/1) Segmentation fault (core dumped)"

and that's it. 
Has anyone experienced this error before?

Here some info:
octomap version 1.9.0
Ubuntu 18.04.3 LTS
GNU 7.4.0 (C & C++)
libQGLViewer-qt4
qmake 4.8.7

Thanks and have a great day!
pxl-accname

**Comment by trunc8** [comment]
@ahornung is #306 related to this?

**Comment by LiShuaixin** [comment]
@pxl-accname  Hi, have you solved the issue? I got the same problem

**Comment by pxl-accname** [comment]
Hi

yes/no.
Shortly after I had to reset my system and reinstall everything.
The error was gone after the reset. There was probably someone wrong going
on with my system.
So I dont have any idea where the problem was coming from.

**Comment by ahornung** [comment]
Probably an issue with local file permission - could it be that you mixed some commands as root (or with sudo) and some as user? The segmentation fault could have been from mixing different library versions.
