### ISSUE TITLE
Is it possible to generate signed distance fields from the dynamicEDT3D module?

### ISSUE THREAD

**Issue by saihv** [OctoMap/octomap#271]
The signed distance field, as is typically used in mapping/planning modules (e.g. voxblox), stores a signed Euclidean distance to the closest "object surface" for every point depending on whether the query point is inside the object or outside. Hence, in free space, this distance can be taken to be positive, and in occupied space, negative. 

Is it possible to construct a "signed" distance field with the current functionality of the dynamicEDT3D module? When queried from occupied voxels, instead of returning 0, the module would have to instead return the distance to the nearest free voxel (with a flipped sign).

**Comment by ahornung** [comment]
That's probably possible, but needs to be implemented. I'm closing this question for inactivity, if you don't mind.
