### ISSUE TITLE
Is it possible to visualize ColorOcTree in Octovis?

### ISSUE THREAD

**Issue by caiwan** [OctoMap/octomap#272]
Hi,

I have implemented several segmentation methods, and other kind of weighting and classifications on voxel maps for our application, with extending the existing tree implementations to represent those information there. However our application has an export feature which can export different values stored represented as colors. My approach is simply create an instance `ColoredOcTree`, copy the existing tree by iterating through the leaves and populate the occupancy based on them with `updateNode`, then set the color of the returning node using a simple LUT. This works flawlessly, octoviz is able to load it without issues, but I was not able see any assigned color, and did not found anything related. I've swiped though the menus, but I still had lo luck. My assumption was that It's able to store colors, it should be able to visualize it. I need this so badly.

I'm using `1.9.1` version right now.

Is there a legitimate way to visualize custom colors in octoviz? If it's not is it planned to have in the future? If it's not is there a way to add this feature in some way? 

Thanks for your support.

**Comment by ahornung** [comment]
Yes, you can visualize a ColorOcTree using octovis and it should work out of the box. The color information is stored in the .ot file format (not .bt though!).

You can try to open "RGBD freiburg1_360" from the dataset repository at http://ais.informatik.uni-freiburg.de/projects/datasets/octomap/

Maybe the color information does not correctly end up in your stored file?

**Comment by caiwan** [comment]
Thank you very much. However It was not clear according to the documentation I've found.
