### ISSUE TITLE
How to convert a octree to a fixed size H*W*L tensor

### ISSUE THREAD

**Issue by turboxin** [OctoMap/octomap#276]
Sorry to bother you. 
I am new to octomap. Now I have create the octree object and insert the point cloud into the octree. Is there any way to convert this octree to a fixed sized tensor of H*W*L , where H=h/d, W=w/d, L=l/d, h,w,l are predefined range and d is grid size.
Can you give me some advice?

**Comment by QiruiZhang** [comment]
I think you can probably walk the whole tensor grid by grid and for each of them, input the 3D coordinate into the given OctoMap to check its occupancy. I think the API supports that very well. Kind of a reverse check, hope it works.
