### ISSUE TITLE
Delete nodes outside a bounding box Assert

### ISSUE THREAD

**Issue by martinakos** [OctoMap/octomap#283]
I've written a function to delete the nodes outside a bounding box. 
The function seems to work well in release mode but if I build it with debug information it always fails in an assert:  
octomap/octomap/include/octomap/OcTreeDataNode.hxx:69: octomap::OcTreeDataNode<T>::~OcTreeDataNode() [with T = float]: Assertion `children == NULL' failed.

which makes me think I'm doing something wrong, but I can't find what is it.  any ideas?
The function is:

```
bool OctomapServer::clear_outside_BBX(point3d &min, point3d &max){

  int count = 0;
  octomap::OcTreeKey minKey, maxKey;
  if (!m_octree->coordToKeyChecked(min, minKey) || !m_octree->coordToKeyChecked(max, maxKey)){
    return false;
  }

  for(OcTreeT::leaf_iterator it = m_octree->begin_leafs(),
      end=m_octree->end_leafs(); it!= end; ++it){
    // check if outside of bbx:
    OcTreeKey k = it.getKey();
    if  (k[0] < minKey[0] || k[1] < minKey[1] || k[2] < minKey[2]
        || k[0] > maxKey[0] || k[1] > maxKey[1] || k[2] > maxKey[2]){
        m_octree->deleteNode(k, it.getDepth());
      ++count;
    }
  }

  ROS_DEBUG("Number of voxels removed outside local area: %i", count);
  return true;
}
```

**Comment by martinakos** [comment]
If I attach QtCreator debugger I see this at the point of the failed assert:
![image](https://user-images.githubusercontent.com/2371869/75974910-7efd6b80-5ecf-11ea-95d9-cbd5e4888b09.png)
![image](https://user-images.githubusercontent.com/2371869/75974955-950b2c00-5ecf-11ea-93ee-51e7b53eabac.png)

so children value is 0x0 which I guess it should make the assert true. maybe there is some type mismatch between children and NULL?

**Comment by ahornung** [comment]
You are modifying the OcTree while traversing it with an iterator, which is not safe and will eventuall fail. Best store the keys and delete them all in a batch afterwards.

**Comment by martinakos** [comment]
It makes sense. But I only used this code because I found the same code in a function in **octomap/octovis/src/ViewerGui.cpp 
void ViewerGui::on_actionDelete_nodes_outside_of_selection_triggered()**
so I thought it was the way to do it.

There must be something else going on as the following code also triggers the same assert in debug mode:

```
bool OctomapServer::clear_outside_BBX(point3d &min, point3d &max){

  octomap::OcTreeKey minKey, maxKey;
  if (!m_octree->coordToKeyChecked(min, minKey) || !m_octree->coordToKeyChecked(max, maxKey)){
    return false;
  }

  vector<pair<OcTreeKey, unsigned int>> keys;
  for(OcTreeT::leaf_iterator it = m_octree->begin_leafs(),
      end=m_octree->end_leafs(); it!= end; ++it){
    // check if outside of bbx:
    OcTreeKey k = it.getKey();
    if  (k[0] < minKey[0] || k[1] < minKey[1] || k[2] < minKey[2]
        || k[0] > maxKey[0] || k[1] > maxKey[1] || k[2] > maxKey[2]){
        keys.push_back(make_pair(k, it.getDepth()));
    }
  }

  for(auto k:keys)
    m_octree->deleteNode(k.first, k.second);

  ROS_DEBUG("Number of voxels removed outside local area: %i", keys.size() );
  return true;
}
```

**Comment by martinakos** [comment]
for the moment I'm commenting the assert to continue my work in debug mode.

**Comment by xinyiz** [comment]
I am getting the same problem when trying to call deleteNode.

Code:

``` 
  for (OcTree::leaf_iterator it = tree_->begin_leafs(), end = tree_->end_leafs(); it != end; ++it) {
     if (it->getValue() < 0.0001) {
       tree_->deleteNode(it.getKey(),it.getDepth());
     }
  }
```

Stack trace:

**octomap::OcTreeDataNode<float>::~OcTreeDataNode() [T = float]: children == __null**
WARNING: thread.cc:1831     @     0x7f14d9e27300  __assert_fail
WARNING: thread.cc:1831     @     0x7f14dda9209e  octomap::OcTreeDataNode<>::~OcTreeDataNode()
WARNING: thread.cc:1831     @     0x7f14dda91e58 
 octomap::OcTreeNode::~OcTreeNode()
octomap::OcTreeBaseImpl<>::deleteNodeChild()
...
...
octomap::OcTreeBaseImpl<>::deleteNodeRecurs()
WARNING: thread.cc:1831     @     0x7f14ddb60f37  octomap::OcTreeBaseImpl<>::deleteNodeRecurs()
WARNING: thread.cc:1831     @     0x7f14ddb60f37  octomap::OcTreeBaseImpl<>::deleteNodeRecurs()
WARNING: thread.cc:1831     @     0x7f14ddb60f37  octomap::OcTreeBaseImpl<>::deleteNodeRecurs()
WARNING: thread.cc:1831     @     0x7f14ddb4e5bc  
octomap::OcTreeBaseImpl<>::deleteNode()

I also checked and there are no children, yet the assert fails
