### ISSUE TITLE
Release octomap to Noetic?

### ISSUE THREAD

**Issue by sloretz** [OctoMap/octomap#285]
Would you mind releasing `octomap` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 55 repos need it.

I'm not sure how much work it will need. At a minimum it needs #284.

**Comment by wxmerkt** [comment]
I am happy to make the release. Alas, I don't have merge permissions to merge #284.

**Comment by ahornung** [comment]
It's merged now, is that enough for a ROS release @wxmerkt ?

**Comment by wxmerkt** [comment]
Perfect, thank you. Can you also please make a release/update package.xml version and add a tag? I don't have write permissions on the repository, otherwise happy to do it as well.

**Comment by ahornung** [comment]
Done: https://github.com/OctoMap/octomap/releases/tag/v1.9.4

**Comment by wxmerkt** [comment]
Thank you, I will make the ROS release.

**Comment by wxmerkt** [comment]
Sorry for the trouble. We first need to update the package dependencies (cf. #286) as recently Qt5 became default (in #280). This _may_ work just fine, but there's a possibility we also need to upstream `libqglviewer-qt5` as a rosdep key in addition to that.

I will look into updating CI with `industrial_ci` in the near future to catch these cases.

**Comment by wxmerkt** [comment]
@sloretz I realised that octomap/octovis are directly in Debian and thus in Ubuntu Focal with version 1.9.3, cf. https://packages.ubuntu.com/focal/allpackages

As thus, do you want me to make a bloom-release or default to the Debian/Ubuntu released versions?

**Comment by sloretz** [comment]
> I realised that octomap/octovis are directly in Debian and thus in Ubuntu Focal with version 1.9.3
> ...
> As thus, do you want me to make a bloom-release or default to the Debian/Ubuntu released versions?

@wxmerkt Oh that's great! I guess it depends on how big the `1.9.x` changes are. It looks like [Debian Buster](https://packages.debian.org/buster/liboctomap1.8) and [Fedora 32](https://src.fedoraproject.org/rpms/octomap) have `1.8.1`. Is it feasible for users to support `1.8.x` and `1.9.x` in the same codebase? While Debian and Fedora are only recommended support platforms, I wouldn't want them to miss out if some important features are only available on Focal. Do you think Debian and Fedora users would greatly miss the newer features?

**Comment by wxmerkt** [comment]
There's a few changes and bug fixes in 1.9. I am happy to make the ROS release, to also allow us to update/iterate when new fixes come in over the long support horizon of Noetic (as the final ROS1 distro).

I am waiting for a rosdep key upstream and then would require a new release of Octomap (including #286).

**Comment by ahornung** [comment]
> @sloretz I realised that octomap/octovis are directly in Debian and thus in Ubuntu Focal with version 1.9.3, cf. https://packages.ubuntu.com/focal/allpackages:
> 
>     * [liboctomap1.9](https://packages.ubuntu.com/focal/liboctomap1.9)
> 
> 
> As thus, do you want me to make a bloom-release or default to the Debian/Ubuntu released versions?

I think it makes sense to get a version released directly into ROS in addition, it'll allow to have faster iterations for updates. The OS-supplied and ROS versions should get along, but I've never tested it myself.

**Comment by ahornung** [comment]
@wxmerkt : v1.9.5 is release to contain the updated Qt5 dependency for octovis.

**Comment by wxmerkt** [comment]
Thank you - release is out. However, RPM-based distributions (e.g. Fedora) are excluded due to missing `libqglviewer2` dependency.

https://github.com/ros/rosdistro/pull/24245

**Comment by sloretz** [comment]
Thank you!
