### ISSUE TITLE
Creating octree with graph2tree causes 'out of bounds in computeRayKeys' message

### ISSUE THREAD

**Issue by justin-bode** [OctoMap/octomap#289]
I created a log file with a global coordinate system (ECEF). I was able to run log2graph successfully without errors. However, when I run graph2tree on the resulting graph file I am inundated with warning messages saying:

WARNING: coordinates ( (302584 -5.24049e+06 3.61142e+06) -> (302723 -5.24084e+06 3.61068e+06)) out of bounds in computeRayKeys

Is there some kind of limit on the ray tracing values?

**Comment by ahornung** [comment]
Please check the paper describing the approach. All octree coordinates have a limit depending on the used resolution. I would suggest to transform to a local coordinate system instead.

**Comment by justin-bode** [comment]
Thanks.
