### ISSUE TITLE
OctoMap with CUDA or OpenCL

### ISSUE THREAD

**Issue by ahmedshafeeq** [OctoMap/octomap#29]
I think it'll be cool to have OctoMap implemented in CUDA or OpenCL to speed things up even more.

**Comment by maxtom** [comment]
Is there any new progress in Octomap and CUDA combination ?

**Comment by Squelsh** [comment]
Nope. But if you don't have to put complex datatypes into your octree nodes, just download GPU-Voxels and have a try.

**Comment by Squelsh** [comment]
I just spent some time in investigating the OctoMap API and the collision check implementation of FCL that collides URDF-models with an Octree.

Long story short: The approaches are so different, that this can not be solved by intelligent wrapping / interfacing.

Longer version: FCL works with a Bounding Volume Hierarchy (a space dividing tree structure) and recursively iterates over models to lookup Voxels in the Octomap selectively. On the other side, GPU-Voxels uses an articulated pointcloud-representation as robot model and collides this with our own Octree implementation. This is done in a highly parallel manner, so we don't need a BVH.

So, when someone needs a collision check between a URDF-Robot and a live pointcloud, GPU-Voxels is magnitudes faster than OctoMap, as we can update our GPU-Octree with the data of several Kinects at full framerate AND do collision checking in parallel.
But as soon as you need a templated Octree with your own Voxel-DataTypes, use OctoMap.

Unfortunately I don't see a way to integrate this into MoveIt / FCL in a straight forward manner. So we stick with our own planners.

Regarding an OctoMap compatible API the insertion of Pointclouds is no problem, but it makes absolutely no sense to query single coordinates / voxels in GPU-Voxels in a serial fashion, as it is done with OctoMap. We can query whole pointclouds with a single call in a millisecond but serialization would nevertheless destroy performance.

**Comment by ahornung** [comment]
Thanks for the detailed clarification, Andreas. I'm closing this issue for now.
