### ISSUE TITLE
When I Cmake, there is an error in octovis

### ISSUE THREAD

**Issue by maguangyan** [OctoMap/octomap#292]
-- viewer octovis will be built
CMake Error at octovis/CMakeLists_src.txt:3 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

i am in ubuntu14.04 and QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu

**Comment by wxmerkt** [comment]
Octovis now defaults to Qt5. You can change it by configuring with `cmake .. -DOCTOVIS_QT5=OFF`

**Comment by ahornung** [comment]
#298 should have fixed this, could you try again with the latest updates from the devel branch?

**Comment by maguangyan** [comment]
i am in ubuntu16.04  now，and the error is has disappeared ,thanks for your help！
