### ISSUE TITLE
Display of Octomap data in Unity. 

### ISSUE THREAD

**Issue by Caveats** [OctoMap/octomap#294]
We are looking at Octomap as a visualisation means for sparse mapping - the end user interface is based in Unity to allow ease of use (and on a device). Has there been any successful ports or examples of using an Octree - feed from Octomap into Unity (or similar)?

**Comment by kingjin94** [comment]
Maybe this project might help? https://github.com/Alexander-Scott/OctoMapSharp

**Comment by Caveats** [comment]
Kingjin94 that's helpful. We did check it out but it looks like the dev only ported part of the methods for what then looks like a terrain based robot fighting game. So it wasn't the win we'd hoped for. (sorry can't find the link but if you sleuth git hub you can find it).

The solution was to change the stack and generate an octomap then pull out the data you want from that in Unity. It's a lot less data and cleaner. At the end of the day you still have ros and unity running. Also you find that unity instantiation of all that data causes some challenges depending on your leaf depth. 

Same issue with point clouds. It's not light weight and doesn't add as much as resolved info in our use case. 

Plus whilst unity can run octree /. Octomap, that's probabaly the wrong use for us. 

Parroting my dev team. Hope that helps.
