### ISSUE TITLE
How information is integrated if no ray is reflected from environment.

### ISSUE THREAD

**Issue by mohit-ludhiyani** [OctoMap/octomap#301]
Consider a scenario where drone is in mid air,  hence, no ray is reflected. How will insert ray function work here?  Does no reflection of ray is interpreted as free space??

**Comment by ahornung** [comment]
Yes, this works as you describe it if the corresponding end points are in the inserted scans / point clouds with a range value >= max range.

**Comment by mohit-ludhiyani** [comment]
Thanks for the quick reply, I just wanted to confirm :
1.) Should the end points always lie on the obstacle? 
2.) What if rays from sensor does not reflect at all from any surface, in this case also will map be updated?? Though the point cloud will be empty, but no reflection also means free volume around.

I am asking this question because in the case of outdoor experiments frequently it happens that no obstacle is in FOV of sensor(hence no ray reflected), and in that case I noticed the environment around robot is not updated as free space by the Octomap.  

My question may look weird, I am sorry but I need this information for some development work.

**Comment by mohit-ludhiyani** [comment]
Can someone please fill me on the information asked above. It would be very helpful.

**Comment by ahornung** [comment]
Check the [documentation of insertRay](https://octomap.github.io/octomap/doc/classoctomap_1_1OccupancyOcTreeBase.html#a3c1c2678e33a791df715affa6ea03dcd), it will tell you exactly that. Free space will be updated / cleared up to the max_range parameter (if set). So if you want to update free space with non-existing points (e.g. an "empty" sparse point cloud), you first need to fill it with correct max_range reading (at least max_range distance away from the sensor origin).

**Comment by RhysMcK** [comment]
Im not quite sure i follow @ahornung.  `insertRay` will clear occupied cells along a ray to a given end point ( or to the maximum range if the end points is beyond this). In either case it requires an actual point to query. In @mohit-ludhiyani he hasn't got any points, he surrounded by free space and may wish to clear any occupied cells in his FOV.

**Comment by ahornung** [comment]
> only real way i see that this is possible is to make your sensor data return points at your maximum range.

Yes, either that or fill missing data in the point cloud with max_range readings, located correctly at their respective reading angle / position.

**Comment by mohit-ludhiyani** [comment]
Thanks guys. As advised, I solved problem by filling the pointcloud.
