### ISSUE TITLE
Performance difference between liboctomap-dev and ros-melodic-octomap-server

### ISSUE THREAD

**Issue by finger563** [OctoMap/octomap#302]
We've found that `liboctomap-dev` (as well as the latest clone+build from this repo) performs 2x slower / worse than the octomap library we installed and used from ROS Melodic - here are some performance numbers of tests written with each build system that load and insert the same scan file:

Version built with ros-melodic-octomap-server:
```
Pointcloud insertion in MapServer done (197885 pts, 0.338715 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.449408 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.437717 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.434922 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.431937 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.322630 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.318412 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.313267 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.310333 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.312590 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.367051 sec average over 10 iterations)
```
Version built with liboctomap-dev / Octomap 1.9.5:
```
Pointcloud insertion in MapServer done (197885 pts, 0.671150 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.811579 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.857094 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.844061 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.801866 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.665780 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.713807 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.692274 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.707798 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.710776 sec)
Pointcloud insertion in MapServer done (197885 pts, 0.747680 sec average over 10 iterations)
```

It is clearly about 2x slower, even though these are running on the same system and calling the exact same octomap function with the exact same data.

Configuration:
launchfile (ROS):
```xml
    <param name="resolution" value="0.02" />
    <param name="sensor_model/max_range" value="6.0" />
    <param name="pointcloud_min_x" value="-3" />
    <param name="pointcloud_max_x" value="3" />
    <param name="pointcloud_min_y" value="-3" />
    <param name="pointcloud_max_y" value="3" />
    <param name="pointcloud_min_z" value="0.2" />
    <param name="pointcloud_max_z" value="3" />
```
config (non-ros)
```json
  "sensor_model/max_range": 6.0,
  "resolution": 0.02,
  "save_pointcloud": true,
  "pointcloud_filename": "pc_scan.node",
  "pointcloud_min_x": -3,
  "pointcloud_max_x": 3,
  "pointcloud_min_y": -3,
  "pointcloud_max_y": 3,
  "pointcloud_min_z": 0.2,
  "pointcloud_max_z": 3,
```

Test Code:

main:
```c++
  try {
    // load the file containing the points
    std::filebuf fb;
    std::string scan_filename = config.value("pointcloud_filename", "pc_scan.node");
    fb.open(scan_filename, std::ios::in);
    if (!fb.is_open()) {
      std::cerr << "Error: could not find scan file '" << scan_filename << "', please make sure to generate one.\n";
      return -1;
    }
    std::istream is(&fb);
    auto node = octomap::ScanNode();
    node.readBinary(is);

    {
      auto start = std::chrono::steady_clock::now();
      size_t num_tests = 10;
      for (size_t i=0; i < num_tests; i++) {
        // now see how long it takes to insert the points
        server.insertScanNode(node);
      }
      auto total_elapsed = std::chrono::duration<double>(std::chrono::steady_clock::now() - start);
      printf("Pointcloud insertion in MapServer done (%zu pts, %f sec average over %zu iterations)\n",
             node.scan->size(), total_elapsed.count() / (double)num_tests, num_tests);
    }

    // cleanup
    fb.close();
  } catch (std::runtime_error &e) {
    std::cout << "test_mapserver_insertion_performance exception: " << e.what() << "\n";
    return -1;
  }
```
Which calls:
```c++
void MapServer::insertScanNode(octomap::ScanNode& node) {
  auto start = std::chrono::steady_clock::now();
  { // protect this code
    std::lock_guard<std::mutex> lock(_octree_mutex);
    // insert octomap::pointcloud into octree
    m_octree->insertPointCloud(*node.scan, node.pose.trans(), m_maxRange, true, true);
    // since we set lazy_eval to true, we need to explicitly call this
    m_octree->updateInnerOccupancy();
    // now we prune the tree (if configured to do so)
    if (m_compressMap)
      m_octree->prune();
  }
  auto total_elapsed = std::chrono::duration<double>(std::chrono::steady_clock::now() - start);
  printf("Pointcloud insertion in MapServer done (%zu pts, %f sec)\n",
         node.scan->size(), total_elapsed.count());
}
```

I've also attached the `pc_scan.node` file for reference - it's simply created by callling `octomap::ScanNode::writeBinary(...)` when receiving and creating our pointcloud data.
[pc_scan.zip](https://github.com/OctoMap/octomap/files/4948022/pc_scan.zip)

**Comment by wxmerkt** [comment]
Hi @finger563,
1. Can you confirm that you are on Ubuntu 18.04 and that the comparison is solely between `liboctomap-dev` (version 1.8.1 on 18.04) and `ros-melodic-octomap` (version 1.9.0)? v1.9.5 has not been released to Melodic - but to Noetic/20.04. For source build, are you using the `devel` branch, i.e. 1.9.5?
2. The launch file parameters suggests you might be using `ros-melodic-octomap-server`? Are you comparing this to your own server?
2. That the library is built in Release mode?
3. That the only difference is against which library you link?

Thanks,
Wolfgang

**Comment by finger563** [comment]
> Hi @finger563,
> 
> 1. Can you confirm that you are on Ubuntu 18.04 and that the comparison is solely between `liboctomap-dev` (version 1.8.1 on 18.04) and `ros-melodic-octomap` (version 1.9.0)? v1.9.5 has not been released to Melodic - but to Noetic/20.04. For source build, are you using the `devel` branch, i.e. 1.9.5?
> 2. The launch file parameters suggests you might be using `ros-melodic-octomap-server`? Are you comparing this to your own server?
> 3. That the library is built in Release mode?
> 4. That the only difference is against which library you link?
> 
> Thanks,
> Wolfgang

Hi @wxmerkt 
1. Yes - I am on Ubuntu 18.04, and I am running a simple test executable whose main consists of the code above.  Regarding the non-ROS library, I have tried both the version provided by `liboctomap-dev` as well as a version I compiled from the latest `devel` branch of this repo so that I could ensure that OpenMP was enabled - this version is closest to 1.9.5 of course.
1. I'm using my own server, which is similar to the `ros-melodic-octomap-server`, it's similarly providing a `octomap::ColorOctree` and handling the insertion / map updates.  Both of the logs I'm showing above are from my own server - either compiled into a ROS node and linking to the `ros-melodic-octomap-server` installed libraries, or compiled into a standalone executable without ROS dependencies and linking against the `liboctomap-dev` libraries.
1. The version I built / installed from source didn't affect performance so I've actually uninstalled and reverted back to the `liboctomap-dev` libraries, but yes I believe it was compiled in Release mode.
1. That is correct - at least to the best of my knowledge, I've isolated it to the octomap library. I've ensured that the point clouds / data are identical by using the same scan node file between them; I've made sure to only call `octomap::OcTree::insertScanNode(...)` when doing performance tests, which means that the only difference between the tests (that I can find) is the implementation of that function (and thus the library which contains that function).

It doesn't really make sense to me TBH, but it's what I've found so I opened this issue so that hopefully you might help me get to the bottom of this :)

(Thanks!)

**Comment by finger563** [comment]
@wxmerkt I think I found the issue - The original code we had  (ROS) was using a ColorOcTree which had `uint8_t r,g,b`, but we went to `float r,g,b` when we moved away from ROS. It seems that even though we're not interacting with the colors (since the `ScanNode` and `octomap::pointcloud` do not contain color information) the change in datatypes is what's causing the massive slowdown - my guess is related to how the data is allocated as the octree adds nodes? Do you have any idea why this might cause such a drastic slowdown and if there's a way for us to circumvent this slowdown?

**Comment by finger563** [comment]
Oddly enough - if I change the `float` to `uint8_t` - i still see the *bad* performance - so something is off with my ColorOcTree compared to the one that comes with octomap....

**Comment by finger563** [comment]
Have confirmed - I can copy and paste the `ColorOcTree.{h, cpp}` from octomap source, build it and use it in my octree, and it is 2x slower - while still using the same datatypes. If I use the `ColorOcTree` provided from `octomap` libraries however, it's the right speed. So something weird is definitely going on here.

**Comment by finger563** [comment]
Final test (sorry for spamming you) - I've confirmed it must be the cmake configuration  / compiler settings I use when compiling my code (and that I use when compiling octomap if i build / install from source).  I see poor performance when using either a custom `ColorOcTree` or even when using octomap's built-in `ColorOcTree` that I've built / installed from source. However, when i use either the pre-built library (`liboctomap-dev` or ROS' `ros-melodic-octomap-server`) then I get better performance.

**Comment by finger563** [comment]
@wxmerkt I don't see anywhere in the READMEs in this repo any compile flags to set other than `-DCMAKE_BUILD_TYPE=Release` and (looking through some code) `-DOCTOMAP_OMP=1`.  What other options are configured for the version that is released, because that is the only difference I can find.

**Comment by wxmerkt** [comment]
Glad to hear you have been able to narrow down the source of the issue. It is hard to debug or provide hypotheses without reproduction examples.

For compilation flags, we do _not_ activate OpenMP by default (see `CMakeLists`: The default is FALSE). The compiler settings apart from `Release` are defined here: https://github.com/OctoMap/octomap/blob/devel/octomap/CMakeModules/CompilerSettings.cmake

**Comment by finger563** [comment]
@wxmerkt  - thanks for pointing me to that; sadly it made no difference w.r.t. performance of the ColorOcTree compiled within my codebase :/

**Comment by finger563** [comment]
@wxmerkt Thanks for your help - since this is now clearly an issue with my build system I'll close this issue :)
