### ISSUE TITLE
Segmentation fault trying to run in docker with GUI

### ISSUE THREAD

**Issue by myFree** [OctoMap/octomap#306]
I am running inside a Ubuntu 18.04.4 docker container, and my host OS is Ubuntu 20.04. My GPU is a Radeon RX 570. I'm using this script to give the container GPU access - https://github.com/ros-planning/moveit/blob/master/.docker/gui-docker

There most definitely could be things not working in my setup, but I can open rViz & Gazebo (I'm not sure when they actually start using GPU / would hard error without it) and the `glxgears` described on http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration works.

After building `make test` all pass; however trying to launch the UI hits

```
(gdb) 
(gdb) file octovis 
Reading symbols from octovis...done.
(gdb) run
Starting program: /repos/octomap/bin/octovis 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Program received signal SIGSEGV, Segmentation fault.
0x00007f28c717c604 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
(gdb) bt
#0  0x00007f28c717c604 in  () at /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#1  0x00007f28cd441783 in call_init (env=0x7ffd88e7aeb8, argv=0x7ffd88e7aea8, argc=1, l=<optimized out>) at dl-init.c:72
#2  0x00007f28cd441783 in _dl_init (main_map=0x7f28cd65a170, argc=1, argv=0x7ffd88e7aea8, env=0x7ffd88e7aeb8) at dl-init.c:119
#3  0x00007f28cd4320ca in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#4  0x0000000000000001 in  ()
#5  0x00007ffd88e7c6eb in  ()
#6  0x0000000000000000 in  ()
```
I saw some issues referencing that having both Qt4 & 5 installed could hit Segmentation fault issues; but checking with the below I only have 4 and not 5 installed in the container.

```
root@bb812a9ddab3:/# qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
root@bb812a9ddab3:/# 
root@bb812a9ddab3:/# 
root@bb812a9ddab3:/# 
root@bb812a9ddab3:/# qmake-qt5 --version
bash: qmake-qt5: command not found
```

Any thoughts on how to troubleshoot further would be most welcome.

**Comment by myFree** [comment]
Building against Qt5 libraries resolved it
I used the below on Debian; not sure if its a slight super set

apt-get install cmake doxygen libqglviewer-dev-qt5 libqt5core5a libqt5opengl5-dev

**Comment by trunc8** [comment]
Thank you so much for this! I've been pulling my hair for 2 days over the segmentation fault error. I came across [your post on Qt forum](https://forum.qt.io/topic/117800/segmentation-fault-debugging-tips/4) and received identical output with gdb. Your comment here finally worked for me.
@Octomap_maintainers, does this denote a bug in the source code? If yes, could I receive some guidance to locate and fix it?(I'm new to open source)

**Comment by myFree** [comment]
The issue I had came down to having the incorrect libraries installed - so was not an issue in the octomap source code.
