### ISSUE TITLE
Question: OctoMap with Laser sensors.

### ISSUE THREAD

**Issue by santiagorg2401** [OctoMap/octomap#313]
Hi,
I am starting a project with a nano UAV equipped with several laser sensors (see: https://store.bitcraze.io/collections/decks/products/multi-ranger-deck), can I use OctoMap in order to create a 3D occupancy grid?

Thank you in advance,
S. Restrepo.

**Comment by ahornung** [comment]
Sure, if your application / sensing setup requires a 3D occupancy grid, you can use OctoMap.

**Comment by santiagorg2401** [comment]
Thank you
