### ISSUE TITLE
Clearing moving obstacles

### ISSUE THREAD

**Issue by aled96** [OctoMap/octomap#314]
Hi,
I am working with a 3D Lidar and Octomap to obtain the map.
If I have a static environment, the map is correct. The problem is when I add and then remove an object. In that case, when I add the object the map introduces it, great. When I remove it, there is no clearing (or at least too slow to be taken into account).

How this can be improved/solved ?
It is possible to give more importance to new scans in order to clear old obstacles ?

Thank you!

**Comment by ahornung** [comment]
Some people use OcTreeStamped for some sort of decay effect (manually implemented). 

Otherwise, you could try to tweak the sensor model (setProbHit / setProbMiss).

**Comment by aled96** [comment]
I have never used OcTreeStamped, now I managed to modify the sensor model parameters and obtain something more reactive. I will close the issue for now, hoping it is reactive enough for what i need
