### ISSUE TITLE
Memory usage optimization in KeyRay?

### ISSUE THREAD

**Issue by OndrejMasopust** [OctoMap/octomap#323]
I was just curious to see how the KeyRay class is implemented. There is one thing that surprised me while looking into the source code.

https://github.com/OctoMap/octomap/blob/a3f38090619d949bcafe82201881acf985d39b00/octomap/include/octomap/OcTreeKey.h#L142-L145

https://github.com/OctoMap/octomap/blob/a3f38090619d949bcafe82201881acf985d39b00/octomap/include/octomap/OcTreeKey.h#L181

It seems to me that the KeyRay constructor allocates memory size for 100000 OcTreeKey elements upon initialization. Isn't this a waste of memory space? I suggest to add the possibility to specify the initial ray size as a constructor input argument. What about that?

**Comment by ahornung** [comment]
That space is only reserved once and needs less than 1MB of memory - usually negligible compared to the octree size in memory. It was a design choice to avoid dynamically resizing the KeyRay storage while computing rays.

**Comment by OndrejMasopust** [comment]
Ok, that makes sense to me now.
