### ISSUE TITLE
BinaryMap versus FullMap? #question

### ISSUE THREAD

**Issue by NicoNorena** [OctoMap/octomap#326]
What is the difference between binaryMap versus FullMap?

tag/ v1.9.6
In RVIZ, I am trying to display the BinaryMap with colors but it looks like the colors in the ColorOctreeNode were not received.
Also, I tried the FullMap  but I get like 4 super big squares , way out of proportion from the map . 

Any ideas for the proper way of publishing the octomap and for rviz to show the map  with colors.

**Comment by ahornung** [comment]
A binary map only contains binary information about occupancy: is the cell occupied or not. So any detailed information about probabilities or color is lost as a compression method.

For specific questions within ROS, best use ROS answers or the ROS-related issue tracking (octomap_mapping or octomap_rviz_plugins).

**Comment by NicoNorena** [comment]
thank you for the explanation.

I will move the question to the octomap_mapping repo.
