### ISSUE TITLE
run octovis with Segmentation fault(core dumped) 

### ISSUE THREAD

**Issue by crashooo** [OctoMap/octomap#329]
The entire project is built perfectly, but when I run the octovis use the following order:
```../bin/octovis ../octomap/share/data/geb079.bt```

This disgusting error shows up:
```Segmentation fault(core dumped) ```

**Comment by crashooo** [comment]
well, I changed my linux kernel from 5.11 to 5.4 and it works finally.....But 5.4 does not fit my graphics card. kind of awkward...

**Comment by wangx1996** [comment]
> well, I changed my linux kernel from 5.11 to 5.4 and it works finally.....But 5.4 does not fit my graphics card. kind of awkward...

I  also meet the porblem. I don't know how to solve it.

**Comment by gcy95** [comment]
me, too...Can anybody solve it?

**Comment by gcy95** [comment]
/usr/include/x86_64-linux-gnu/qt5/QtGui/qopenglext.h:60:0: warning: "GL_GLEXT_VERSION" redefined
 #define GL_GLEXT_VERSION 20170325
 
In file included from /usr/include/GL/gl.h:2050:0,
                 from /usr/include/GL/glu.h:38,
                 from /home/gcy/learn_ros_drill/octomap/octovis/include/octovis/SceneObject.h:37,
                 from /home/gcy/learn_ros_drill/octomap/octovis/include/octovis/OcTreeDrawer.h:28,
                 from /home/gcy/learn_ros_drill/octomap/octovis/src/OcTreeDrawer.cpp:25:
/usr/include/GL/glext.h:54:0: note: this is the location of the previous definition
 #define GL_GLEXT_VERSION 20190911
maybe the compile went wrong here.
