### ISSUE TITLE
Problem using binvox2bt tool

### ISSUE THREAD

**Issue by razekmaiden** [OctoMap/octomap#332]
Hello everybody.

I am writing here because I have problems using the "binvox2bt" tool. For context, I am trying to convert a map generated from AirSim, according to these instructions: [Voxel Grid Generator](https://microsoft.github.io/AirSim/voxel_grid/).

I can correctly generate the map.binvox and view it with the [viewbox](https://www.patrickmin.com/viewvox/) tool.
![viewbox_1](https://user-images.githubusercontent.com/7081707/116085742-1cd06e80-a66d-11eb-9a56-644b741abbbb.png)

However when trying to convert it to map.bt ([ref](https://github.com/OctoMap/octomap/wiki/Importing-Data-into-OctoMap#converting-a-binvox-file-to-an-octree)), the "binvox2bt" tool apparently returns an "empty" map. When opening the * .bt file returned by "binvox2bt", with a text editor, this is what I see.

```
# Octomap OcTree binary file
# (feel free to add / change comments, but leave the first line as it is!)
#
id OcTree
size 0
res 5e-05
data
```

Additionally when executing "binvox2bt", the terminal indicates the following.

```
binvox2bt /home/joseluis/Proyectos/unreal_engine/AirSim/PythonClient/map.binvox
Reading binvox file /home/joseluis/Proyectos/unreal_engine/AirSim/PythonClient/map.binvox.
reading binvox version 1
Generating octree with leaf size 5e-05

Read data: ....................

    read 423442 voxels, skipped 0 (out of bounding box)

Pruning octree

Writing octree to /home/joseluis/Proyectos/unreal_engine/AirSim/PythonClient/map.binvox.bt

done
```

Am I using "binvox2bt" wrong? I appreciate any help.

PS: I am using octomap version 1.9.6 on Ubuntu 18.04, ROS Melodic.

**Comment by leoborgnino** [comment]
Hi, I had the same issue, I use leatherman binvox parser and I changed something related to the res (I think there could be a scale problem).

I changed:

double res = double(scale)/double(maxSide);

for: 

double res = (1.0/double(scale))/double(maxSide);

You can change manually the scale of the binbox(edit the file directly) for 1/scale (if it is 0.1 change to 10), test if the octomap is still empty and let me know. I didn't test it so much so I don't know the exactly root of the problem.

My code is at:

https://github.com/leoborgnino/AirSim/blob/spawn_models/ros/src/airsim_planning_ros_pkgs/src/planning_example.cpp

**Comment by razekmaiden** [comment]
I had some trouble compiling leatherman and your code. However as I have more experience and understanding in python, I looked for an option with python and I found this repository [binvox-rw-py](https://github.com/dimatura/binvox-rw-py), where I can read the map.binvox change the scale and save it again as map_out.binvox. Finally the tool "binvox2bt" it gives me a map.bt with data.

Would you then understand that the problem is generated at the level of AirSim that generates binvox with a wrong scale?

**Comment by ZhanyuGuo** [comment]
Hello @razekmaiden, I meet the same issue :sob:.

I try using `binvox-rw-py` to change my scale from `0.01` to `100.0`, and convert using `binvox2bt`. I finally get a non-empty file, but it is:

![Screenshot from 2023-11-07 21-22-45](https://github.com/OctoMap/octomap/assets/65705518/363a5926-6ae6-4a4b-b6fe-26fdc9176386)

`map.binvox` is correct:

![Screenshot from 2023-11-07 21-28-48](https://github.com/OctoMap/octomap/assets/65705518/651e1a05-8585-4fe8-81a1-b9a9fccb87f0)

But I cannot open the `map_out.binvox` using `viewvox`.

I make my `binvox` using:

```python
import airsim

client = airsim.MultirotorClient()
client.confirmConnection()

center = airsim.Vector3r(0, 0, 0)
client.simCreateVoxelGrid(center, 100, 100, 100, 1, "map.binvox")
```

I have tried many resolutions but it was still not working...

**Comment by ZhanyuGuo** [comment]
> Hello @razekmaiden, I meet the same issue 😭.
> 
> I try using `binvox-rw-py` to change my scale from `0.01` to `100.0`:
> 
> ```python
> import binvox_rw
> 
> with open('map.binvox', 'rb') as f:
>     model = binvox_rw.read_as_3d_array(f)
> 
> model.scale = 1 / model.scale
> 
> with open('map_out.binvox', 'wb') as f:
>     model.write(f)
> ```
> 
> , and convert using `binvox2bt`. I finally get a non-empty file, but it is:
> 
> ![Screenshot from 2023-11-07 21-22-45](https://user-images.githubusercontent.com/65705518/281054999-363a5926-6ae6-4a4b-b6fe-26fdc9176386.png)
> 
> My `map.binvox` is correct:
> 
> ![Screenshot from 2023-11-07 21-28-48](https://user-images.githubusercontent.com/65705518/281055551-651e1a05-8585-4fe8-81a1-b9a9fccb87f0.png)
> 
> But I cannot open the `map_out.binvox` using `viewvox`.
> 
> I make my `map.binvox` using:
> 
> ```python
> import airsim
> 
> client = airsim.MultirotorClient()
> client.confirmConnection()
> 
> center = airsim.Vector3r(0, 0, 0)
> client.simCreateVoxelGrid(center, 100, 100, 100, 1, "map.binvox")
> ```
> 
> I have tried many resolutions but it was still not working...

I find the problem...

While using python3 for `binvox-rw-py`, I should make some modification shown in [this](https://github.com/dimatura/binvox-rw-py/issues/13#issuecomment-651521513).

I made wrong modifications by myself and led to wrong outputs.
