### ISSUE TITLE
python wrappers for octomap

### ISSUE THREAD

**Issue by addy1997** [OctoMap/octomap#334]
Hello there,

I am a researcher specializing in motion planning on high-dimensional surfaces. For my project, I wanted to know where to find python bindings for octomap?

Thanks

**Comment by ahornung** [comment]
I'm not aware of any, but you should be able to bind the C++ API.

**Comment by addy1997** [comment]
> I'm not aware of any, but you should be able to bind the C++ API.

Alright, thanks for that.
