### ISSUE TITLE
ROS2 Galactic Release

### ISSUE THREAD

**Issue by DLu** [OctoMap/octomap#335]

**Comment by wxmerkt** [comment]
A release into Rolling and Galactic is currently blocked as the rosdep key for `libqglviewer2-qt5` is missing on RHEL 8 (cf. [base.yaml here](https://github.com/ros/rosdistro/blob/b275550aed0b200c64f78d1377a597eed77b7428/rosdep/base.yaml#L3925-L3929)). I could not find the package name to add to rosdep/base based on a cursory search - although I found a [RedHat forum post](https://access.redhat.com/discussions/4142491) wondering whether Qt5 development packages are available.

@DLu Is this something you could potentially look into finding/getting added to rosdep base? libqglviewer2-dev-qt5 is required for octovis.

**Comment by ahornung** [comment]
Is there a way to blacklist single packages from a release (even if it's only temporarily) for ROS2? I remember something like that from ROS1...

That way the octomap release could go forward without octovis.

**Comment by DLu** [comment]
It may make sense to split them into two repos. That's what happened to `urdf_tutorial/urdf_sim_tutorial` so the former didn't have gazebo dependencies.

**Comment by wxmerkt** [comment]
I've made a release - https://github.com/ros/rosdistro/pull/29437 - and will blacklist RHEL 8 when the errors come back. I tried finding the missing package on CentOS but couldn't.

**Comment by wep21** [comment]
@wxmerkt Could you also make `rolling` release with `bloom`?

**Comment by wxmerkt** [comment]
Sure - I made the release and ignored RHEL8 based distributions for octovis: https://github.com/ros/rosdistro/pull/29535
