### ISSUE TITLE
Hi, Do we have more Node properties to represent more features of Nodes?

### ISSUE THREAD

**Issue by jediofgever** [OctoMap/octomap#341]
Hello, 
What I want is quite simple and there are workarounds , however I want to know if there is a better approach here. 
I am aware that each node has a probability "value" of being a "hit". Lets say I want to have another feature besides the value of hit. precisely, I want to assign a cost to each individual Node, How to cleanly associate this feature with the Node Without using additional data structures

Thank you for your time.

**Comment by martivilella** [comment]
You can take a look at the `OcTreeGripper` and `OcTreeGripperNode` implementations I developed [here](https://github.com/aut-o-magic/octomap-grasping). The node implementation has one additional boolean attribute besides the default `value`, so you can fork that and easily convert it into your cost attribute.
