### ISSUE TITLE
Not enough inliers found to support a model 

### ISSUE THREAD

**Issue by tomkimsour** [OctoMap/octomap#342]
Hello,

I am using ros kinetic and am actually trying to do mapping with octomap but I can't understand properly what this error mean.
It only prompt when i set ground_filter to true.

Could someone please explain it ?

```
[pcl::SampleConsensusModelPlane::optimizeModelCoefficients] Not enough inliers found to support a model (0)! Returning the same coefficients.
[ INFO] [1621410313.723860512]: PCL segmentation did not find any plane.
[ WARN] [1621410313.723899495]: No ground plane found in scan
```

**Comment by ahornung** [comment]
That's not a message specific to octomap (the core) - please use the octomap_mapping project for issues like that.

The error means that the ground_filter cannot find a ground plane, either because there is not enough data or because the coordinate transforms are wrong.
