### ISSUE TITLE
Doxygen documentation link no longer works

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [OctoMap/octomap#345]
This links seems to not work anymore : https://octomap.github.com/octomap/doc/

**Comment by martivilella** [comment]
Github switched to the `.io` TLD for pages: https://octomap.github.io/octomap/doc/

**Comment by ahornung** [comment]
I fixed some more links in https://github.com/OctoMap/octomap/commit/2b8385e5398a79924bc39e5dac5622f07b8b12f0
