### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by iamarkaj** [OctoMap/octomap#353]
The [online API documentation](https://octomap.github.com/octomap/doc/) link at [Getting Started](https://github.com/OctoMap/octomap/wiki/Compilation-and-Installation-of-OctoMap#getting-started) seems to be broken.
The correct link is [here](https://octomap.github.io/octomap/doc/).

**Comment by wxmerkt** [comment]
Thank you very much for reporting this - I just edited the wiki page to update the link. Please let us know if you come across any other broken links or issues :-)

**Comment by iamarkaj** [comment]
Similar problem [here](https://octomap.github.io/octomap/doc/md_README.html) under DOCUMENTATION

**Comment by iamarkaj** [comment]
Fixed via #354 and #355
