### ISSUE TITLE
octovis: undefined symbol: _ZN8octomath6Pose6DC1ERKS0_

### ISSUE THREAD

**Issue by fishmarch** [OctoMap/octomap#359]
Hello. I could build the octovis successfully, but an error appears when running it.

![Screenshot from 2021-12-21 17-04-19](https://user-images.githubusercontent.com/40687908/146902632-f48ee8ac-e482-4444-bb17-22ed1ed91889.png)

**Comment by wxmerkt** [comment]
Which operating system are you on and how did you configure/build?

**Comment by fishmarch** [comment]
I am working on Ubuntu 20.04. I build it just following the instruction in README.md. Maybe some problems with Qt? I am using Qt5.

**Comment by wxmerkt** [comment]
I've just tried it locally on 20.04 and it works. Can you check `ldd ./bin/octovis` and whether it resolves to `lib/...` relative to the source directory of the repository?

**Comment by fishmarch** [comment]
Here are the outputs. Could you find any problem
![Screenshot from 2021-12-24 13-48-45](https://user-images.githubusercontent.com/40687908/147321805-fa0fd431-0195-4ca4-afb5-fad90aa6fb9d.png)
?

**Comment by wxmerkt** [comment]
It picks up `liboctomap`/`liboctomath` from `/lib` and `liboctovis` from `/home/xiaoyu/myLibs/...`. I would expect that all of them get picked up from `./lib/` i.e. relative to the root of the repository (which I suspect is myLibs/octomap). Either the configure step went wrong or you need to amend your  `LD_LIBRARY_PATH` to prepend the current directory.

**Comment by fishmarch** [comment]
Although I do not know the reason yet, the problem disappears now. Thanks a lot.
