### ISSUE TITLE
Too much ram occupation of octovis

### ISSUE THREAD

**Issue by addriumruss** [OctoMap/octomap#388]
Hey guys,
I run octovis under windows 10. 
Just load one .bt file, 900kb, the ram occupation of octovis is up to 1.5G。
Why does it need so much ram? 
Is there anyway to reduce it?

**Comment by ahornung** [comment]
Reduce the level of detail for visualizuation / "tree depth cutoff". This will visualize a coarser version. The visualization needs to create one voxel per occupied cell, this needs quite some memory.
