### ISSUE TITLE
Get Neighbour-Nodes from a node

### ISSUE THREAD

**Issue by ghost** [OctoMap/octomap#42]
Is it possible to get neighbouring nodes from a node?
I would like to use the leaf_iterator (or tree_iterator) and to extract the information from the neighbours of every node.

Thank you!

**Comment by alexjung** [comment]
Does this also apply to keys of nodes in coarser resolution? Is +1 still +res (getResolution()) or +res in this depth of the tree?

**Comment by ahornung** [comment]
Keys only represent the coordinates at the tree resolution (voxel coordinates). With a depth and the function `computeIndexKey(..)` you can get a coarser key, but need to consider the depth yourself (e.g. add +2 at depth 15, +4 at 14 and so on).

**Comment by luqman21** [comment]
I am facing similar issue. I am feeding Octomap::PointCloud. by using iterator I found the octreeNode of each occupied node. But How to find keys of each occupied node from OctreeNode ?
I want to find the neighbours of each occupied node.

**Comment by BoltzmannBrain** [comment]
Once upon a time there was [OcTreeLUT](https://github.com/OctoMap/octomap/blob/2e79c5307b6b30c6e72fcfbab4f38f2339786d05/octomap/include/octomap/OcTreeLUT.h#L64) that implemented a lookup table to compute keys of neighbor cells directly.
