### ISSUE TITLE
A problem with the rviz plugin

### ISSUE THREAD

**Issue by Skeptic9793** [OctoMap/octomap#420]
My Ubuntu version is 20.04, The ROS version is noetic. When I used the command `sudo apt-get install ros noetic octomap *` to install octomap, I found that the octomap plugin cannot be used in rviz. Once the relevant plugins are added, The rviz process will immediately die.
skc@skc1:~$ rosrun rviz rviz
[ INFO] [1716464630.107353140]: rviz version 1.14.20
[ INFO] [1716464630.107399999]: compiled against Qt version 5.12.8
[ INFO] [1716464630.107411485]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1716464630.115797038]: Forcing OpenGl version 0.
[ INFO] [1716464630.549960619]: Stereo is NOT SUPPORTED
[ INFO] [1716464630.550091943]: OpenGL device: NVIDIA GeForce GTX 1650/PCIe/SSE2
[ INFO] [1716464630.550123699]: OpenGl version: 4.6 (GLSL 4.6).
/opt/ros/noetic/lib/rviz/rviz: symbol lookup error: /opt/ros/noetic/lib//liboctomap_rviz_plugins.so: undefined symbol: _ZN4rviz16RosTopicPropertyC1ERK7QStringS3_S3_S3_PNS_8PropertyE

**Comment by wxmerkt** [comment]
Hi, I just tried to reproduce this with the latest binaries (rebuilt May 21st) and couldn't. Did you re-source your terminal after installing? Could you show the output of `ldd  /opt/ros/noetic/lib//liboctomap_rviz_plugins.so`?

**Comment by Skeptic9793** [comment]
> Hi, I just tried to reproduce this with the latest binaries (rebuilt May 21st) and couldn't. Did you re-source your terminal after installing? Could you show the output of `ldd /opt/ros/noetic/lib//liboctomap_rviz_plugins.so`?

Hi, I reinstalled ROS on the day I raised the issue, and now the issue has been resolved. Unfortunately, I cannot provide this output

**Comment by wxmerkt** [comment]
Ok, could you close the issue then please? Glad to hear it's resolved
