### ISSUE TITLE
CMake Error while using catkin_make

### ISSUE THREAD

**Issue by ArdEngineer** [OctoMap/octomap#422]
![屏幕截图 2024-08-01 224051](https://github.com/user-attachments/assets/8dba8447-6ac7-4aa4-87aa-93e7358d7e49)
I don't know how to handle this error...

**Comment by ArdEngineer** [comment]
CMake throw error "'boost::placeholders' has not been declared"

**Comment by ahornung** [comment]
This appears to be an error when compiling the ROS octomap packages (octomap_mapping), please use some general ROS support or the issue tracker there: https://github.com/OctoMap/octomap_mapping
