### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by JulioPlaced** [OctoMap/octomap#424]
Hello, are there any plans to maintain the ROS2 branch? It currently seems a bit outdated.

**Comment by ahornung** [comment]
I'm not actively working or maintaining that branch. I'm pretty sure it's not needed anymore for the core library to use it within ROS2, but maybe an active ROS2 user can shed some insights.

**Comment by wxmerkt** [comment]
The `ros2` branch is outdated and wasn't used for releases either. ROS2 releases were made from `devel`; and as of recently Octomap has been removed as a vendored package in ROS2 - it uses the upstream system-provided packages instead. We should likely delete the `ros2` branch in this repository or mark it as deprecated/archived.

**Comment by ahornung** [comment]
Done as suggested!
