### ISSUE TITLE
Compiling Octomap under Windows 7 VC++2008, linker error DLL paths

### ISSUE THREAD

**Issue by tmdiv** [OctoMap/octomap#47]
While compiling Octomap liboctomap.dll was not found by exampleEDT3D, exampleEDTOctomap, octovis.
Visual produces this DLL for debug in c:/octomap-1.6.1/lib/debug, for release in c:/octomap-1.6.1/lib/release. In the output the missing lib was supposed to be in ..\..\..\lib\liboctomap.dll (not divided to release and debug). How to force cmake configs to set dll paths correctly ?

**Comment by ahornung** [comment]
Fixed now, the CMake config for windows now drops the `Release` and `Debug` path prefixes and puts the .lib files for linking into the exported CMake configs.
