### ISSUE TITLE
Sonar measurement

### ISSUE THREAD

**Issue by sfoix** [OctoMap/octomap#62]
Hi,

I've been looking at the code and I don't see any function for sonar measurements update but only for laser and pointclouds. Sonar measurements have a cone structure that has to be updated correctly in order to have a better estimate of our environment's belief. Is there anybody working on that? I've just started thinking about a workaround. Suggestions are welcome. And code even more ;)

Regards,

Sergi.

**Comment by niklas102** [comment]
Hello,
Did you worked on that ?
