### ISSUE TITLE
How can I insert the PointCloud correctly?

### ISSUE THREAD

**Issue by qiqipchy** [OctoMap/octomap#76]
Hello,I has used the kinect to capture images and convertd them to PointCloud.The data format is(x,y,z,rgb).
And I delete the last column to make it as(x,y,z).Then I use the function insertPointCloud(endpoint,origin).
I regard the point(x,y,z) as the endpoint and origin point is (0,0,0).I loop through all the data and indeed get an .ot file and can octovis it.But I can not get the .ot file correctly always.And I try the function 
insertPointCloudRays() and updateNode(),they do not work.Is anything wrong?

I use the dataset rgbdslam_freiburg_desktop from the website.I never get the correct one ,depressed.I notice
that you have generated successfully on the website named "RGBD freiburg1_360".I want to do,too.
And I read the "test_color.cpp" and I think if I want a colored one.I must use the founction undateNode(origin,occpuied) to insert the Pointcloud data.I consider that the parameter "occpuied" is always "true".Because the point has been measured.Am I right?

So can you tell me how to insert Pointcloud data correctly and make a colored one just like "RGBD freiburg1_360"?I'll appreciate it too much.

**Comment by ahornung** [comment]
Please don't cross-post, see the answer at the mailng list: https://groups.google.com/forum/#!topic/octomap/RZHSCJSJ7j0
