### ISSUE TITLE
please release for Jade

### ISSUE THREAD

**Issue by vrabaud** [OctoMap/octomap#80]
Thx
http://wiki.ros.org/jade/Planning/Maintenance

**Comment by scpeters** [comment]
+1, this is blocking `gazebo_ros_pkgs` among other things

**Comment by wjwwood** [comment]
+1, @ahornung I can help if you don't have time for the initial release (and it's the same as indigo).

**Comment by ahornung** [comment]
I just tried releasing with `bloom-release octomap --track jade --rosdistro jade --new-track`, anwering all questions with the defaults (should be fine, same as for indigo). No success with the following error:
```
Failed to checkout to 'debian/fuerte/octomap' because the working directory has local changes

++ git status:

Auf Branch master
Ihr Branch ist vor 'origin/master' um 3 Commits.
  (»git push« benutzen, um lokale Übertragungen zu veröffentlichen)

nichts zu committen, Arbeitsverzeichnis unverändert
Failed to checkout to 'patches/debian/fuerte/octomap' because the working directory has local changes

++ git status:

Auf Branch master
Ihr Branch ist vor 'origin/master' um 3 Commits.
  (»git push« benutzen, um lokale Übertragungen zu veröffentlichen)

nichts zu committen, Arbeitsverzeichnis unverändert
Traceback (most recent call last):
  File "/usr/bin/bloom-release", line 9, in <module>
    load_entry_point('bloom==0.5.19', 'console_scripts', 'bloom-release')()
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1302, in main
    args.override_release_repository_push_url)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1187, in perform_release
    tracks_dict = create_a_new_track(track, tracks_dict)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1183, in create_a_new_track
    check_for_patches_and_ignores(release_repo.get_path())
  File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1123, in check_for_patches_and_ignores
    if [f for f in ls_tree(patch_branch) if f.endswith('.patch')]:
TypeError: 'NoneType' object is not iterable
```


There are more lines `Failed to checkout to 'bloom' because the working directory has local changes` at the beginning as well. Any ideas @wjwwood?

The release should be identical to indigo, v1.6.8 from upstream.

**Comment by wjwwood** [comment]
You have to use the english version of `git`: https://github.com/ros-infrastructure/bloom/issues/300

I'm not sure that's the issue, but I have feeling it is. I think you ran into it before, but we still haven't changed anything to fix it in bloom...

**Comment by ahornung** [comment]
Ah, right, looks like I ran into this again...   trying with the lang exports now.

**Comment by ahornung** [comment]
Almost there, just need to have qglviewer in rosdep: https://github.com/ros/rosdistro/pull/8073

**Comment by wjwwood** [comment]
Go for it.

**Comment by ahornung** [comment]
:white_check_mark:  Release pushed
