### ISSUE TITLE
uninstall target for the complete project (all 3 packages)

### ISSUE THREAD

**Issue by thunderbirdtr** [OctoMap/octomap#82]
Hello ; Seems to be we have uninstall problem on octomap I was trying to rebuild for my ROS system and I just noticed there is a little problem on the delete so ; the error is 
```
CMake Error at cmake_uninstall.cmake:2 (message):
  Cannot find install manifest:
  "/home/thunderbirdtr/ros_build/octomap/build/octomap/install_manifest.txt"

octomap/CMakeFiles/uninstall.dir/build.make:49: recipe for target 'octomap/CMakeFiles/uninstall' failed
make[3]: *** [octomap/CMakeFiles/uninstall] Error 1
CMakeFiles/Makefile2:111: recipe for target 'octomap/CMakeFiles/uninstall.dir/all' failed
make[2]: *** [octomap/CMakeFiles/uninstall.dir/all] Error 2
CMakeFiles/Makefile2:119: recipe for target 'octomap/CMakeFiles/uninstall.dir/rule' failed
make[1]: *** [octomap/CMakeFiles/uninstall.dir/rule] Error 2
Makefile:193: recipe for target 'uninstall' failed
make: *** [uninstall] Error 2
```

All I did for solving this; 

```
cd /home/thunderbirdtr/ros_build/octomap/build (manifest file in here and copy into the "octomap" folder according the cmake_uninstall file) 
cp -r install_manifest.txt octomap/
```
and now "make uninstall" command line is working now.  

I hope I can help a little bit 
Thank you have nice day :)

**Comment by ahornung** [comment]
Indeed, the uninstall target is not working when compiling the complete project (octomap, octovis and dynamicEDT3D) but only for the octomap package in its own subdirectory. Should be fixed! Since the install_manifest.txt contains all filenames that shouldn't be too hard on the CMake level without manually copying files.
