### ISSUE TITLE
Merging the function for updating the octomap from contact sensors

### ISSUE THREAD

**Issue by mmurooka** [OctoMap/octomap#88]
I'd like some advice about merging my work to octomap repositories.

I'm working on the enviroment modeling by integrating the vision and contact sensor.

I created by my branches for Octomap/octomap[1], Octomap/octomap_mapping[2], Octomap/octomap_msgs[3] and added many changes.

[1] https://github.com/mmurooka/octomap/tree/insert-contact-sensor
[2] https://github.com/mmurooka/octomap_mapping/tree/insert-contact-sensor
[3] https://github.com/mmurooka/octomap_msgs/tree/insert-contact-sensor

The grids occupied by robot links are updated as missed; the grids on the surface of robot links are updated as hit if contact is detected.
Using my branches, the update by contact sensor becomes possible as shown in the following movies.

- Test in gazebo
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/file/d/0B5qanGnXorOuM0lKMGRiZEpacGc/view?usp=sharing
- Real robot demo
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/file/d/0B5qanGnXorOuNXJ5blRaNTNwTDg/view?usp=sharing

Now, I'd like to move my work from my branches to common branches.

I have many changes specific to the contact sensor update, and think that merging these changes to origin/master of octomap repositories is difficult.
(For example, octomap_server depends on pr2_navigation_self_filter in my branches.)

I think that creating the inheritance class is realistic.
So, I generated the inheritance class of OctomapServer, OctomapServerContact[4] in our lab repository.
Some changes of OctomapServer are still necessary, so I created new branch of OctomapServer[5].
Now, I can use my work with the combination of [1],[4],[5].

I'd like to ask two questions.
- Is it possible to merge the changes in [5] to Octomap/octomap_mapping repository?
- Is it possible to merge the changes in [1] to Octomap/octomap repository? If not, how can I inherit the octomap class? I am confused because Octomap classes are complicated.

[4] https://github.com/mmurooka/jsk_recognition/tree/octomap-contact
[5] https://github.com/mmurooka/octomap_mapping/tree/octomap-contact

Thank you.

**Comment by ahornung** [comment]
Thanks for your detailed explanations! You're right, merging this special functionality into all of the affected octomap packages won't be a good idea. In retrospect, I would even separate the default (ray) sensor model of OctoMap from the core data structure, if it wouldn't mean a major rewrite of the library.
But the class structure should enable derived classes for your cases easily, and if not then I will happily include patches to make inheritance easier.

Concerning question 1: Looks good, only why do you need `publishAll(...)` to be `virtual`? For regular inheritance it's usually not needed

Concerning question 2: Looks to me like a too specialized sensor model that is best suited for a derived octree class. You could create a class ContactOcTree:
`
class ContactOcTree : public OccupancyOcTreeBase <OcTreeNode>
`

and put all specialized update functions and parameters in it. If you need a specialized OcTreeNode, replace `<OcTreeNode>` with your specialized implementation. As an example, have a look at ColorOcTree.h, it's a good example on how to derive a special octree class. In fact, you could even place the class files in your branch of octomap_mapping, which allows you to use the default octomap repository (and thus means one less branch to maintain).

**Comment by mmurooka** [comment]
> Concerning question 1: Looks good, only why do you need publishAll(...) to be virtual? For regular inheritance it's usually not needed

In my inherited class, I override `publishAll` at https://github.com/mmurooka/jsk_recognition/blob/octomap-contact/jsk_octomap_mapping/jsk_octomap_server/src/OctomapServerContact.cpp#L287 and call at https://github.com/mmurooka/jsk_recognition/blob/octomap-contact/jsk_octomap_mapping/jsk_octomap_server/src/OctomapServerContact.cpp#L284 .
If we do not add `virtual` to `publishAll` in the parent class, `publishAll` in the parent class is called in the inherited class.

**Comment by mmurooka** [comment]
> Concerning question 2: Looks to me like a too specialized sensor model that is best suited for a derived octree class.

I created the derived octree class and place the class file in my repository.
https://github.com/jsk-ros-pkg/jsk_recognition/commit/52c8cbebaeb193f72e71dc405caf2c0cb38f9228

So, the only PR that I'd like to merge is https://github.com/OctoMap/octomap_mapping/pull/21 .

Thank you for your advise.
