### ISSUE TITLE
Overflow in KeyHash / Crash with clang

### ISSUE THREAD

**Issue by lorenzoriano** [OctoMap/octomap#90]
In OcTreeKey.h line 100, hashing is done with:

```c++
      size_t operator()(const OcTreeKey& key) const{
        // a hashing function 
        return key.k[0] + 1337*key.k[1] + 345637*key.k[2];
```

even though the return type is size_t, the individual temp variables created by the expression are unsigned short in (the type of key.k[]). This potentially creates an overflow. gcc seems to happily go ahead (with the overflow) while a program compiled with clang (both Linux and Mac) aborts with a runtime crash.

The correct solution is to write something like:

```c++
    struct KeyHash{
      size_t operator()(const OcTreeKey& key) const{
        // a hashing function 
	  size_t a = key.k[0];
	  size_t b = size_t(1337)*size_t(key.k[1]);
	  size_t c = size_t(345637)*size_t(key.k[2]);
	  size_t to_return = a + b + c;
	  return to_return;
//        return key.k[0] + 1337*key.k[1] + 345637*key.k[2];
      }
```
It can be shortened in one line, this is only to illustrate the individual steps. I believe this will also make hashing more efficient (full use of the size_t range).

**Comment by ahornung** [comment]
Good catch, fixed now! 

Although I didn't notice a difference in performance on my machine in the end.

**Comment by lorenzoriano** [comment]
The performance won't be affected, but the crashes with clang compiled code will :smile:

**Comment by ahornung** [comment]
Well, I was hoping for more efficient insertions due to fewer hash collisions!
