### ISSUE TITLE
Non-uniform discretization? 

### ISSUE THREAD

**Issue by ingridqi** [OctoMap/octomap#92]
Does octomap support non-uniform discretization? The launch file only allows me to specific one parameter for resolution, which creates uniform cubes. I would like a have a 1x by 2x by 1.5 x rectangular prism to represent each voxel. Is this a possibility with the current data structure? If so, how do I go about implementing this?

**Comment by ahornung** [comment]
No, unfortunately there are many place that assume the same size of the voxels in all dimensions. If you want to try adjusting the code, the most important places to start will be the OcTreeKey data structures and conversions, as well as ray casting and search methods.
