### ISSUE TITLE
OcTreeNode with 64 bits members crashes

### ISSUE THREAD

**Issue by lsouchet** [OctoMap/octomap#95]
Hello,
I created a OcTreeNodeX64 containing a timestamp stored on 64 bits.
I experienced that when using my new octree, I get an error on linux32, but not on linux64 :
###### *** Error in `octomap/bin/test_octree_x64': free(): invalid pointer: 0x080ec500 ***
when inserting rays.

If I replace my timestampType from int64_t to int32_t, my test passes just fine.

You can check this in PR #94 (https://github.com/OctoMap/octomap/pull/94)

This looks like at some point, we are working on a Node that has already been deleted, but I don't get how such parallel behaviors could appear just because of the data type.
It kind of bothers me as I intend to use more complex node structures and I am not sure about the scalability of this architecture.
Has anyone encountered the same issues or has any thoughts?

Thanks,

**Comment by ahornung** [comment]
Could this be related to Issue #93?

In your example code you don't implement `expandNode`, so there's a chance that different classes get mixed. If the implementations happen to have different sizes (e.g. 32 / 64 bit) errors like the one you see could manifest.

**Comment by ahornung** [comment]
Using the valgrind memcheck I see some errors "Invalid write of size 8" also on linux64. I think the different padding size with 64 bits allow a bit more room, that's why you only see the free()-Error on 32 bit. But the behavior is definitely unwanted.

After copying expandNode() from OcTreeDataNode into your OcTreeX64Node, I can confirm that the errors are gone. I'm closing here and suggest discussing future improvements in Issue #98.

**Comment by ahornung** [comment]
The code in the experimental branch `node-subclassing-tree` aims to resolve this issue cleanly, as described in #98. Would you maybe test it with your use case, @lsouchet? In derived node classes you should no longer need to implement `getChild()`, `expandNode()` or `createChild()` using that branch.

**Comment by lsouchet** [comment]
Thanks, I'll have a look when I get a chance.
Actually the implementation of expandNode() fixed my issue.

Thanks for your help!
